// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Team1.VitalBridge.BackStage.Models.EFModels;

[Index("Email", Name = "UQ__AdminUse__AB6E61647640E06A", IsUnique = true)]
[Index("AdminId", Name = "UQ__AdminUse__AD0500A71AE5B342", IsUnique = true)]
public partial class AdminUser
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("adminId")]
    [StringLength(50)]
    [Unicode(false)]
    public string AdminId { get; set; }

    [Required]
    [Column("name")]
    [StringLength(20)]
    [Unicode(false)]
    public string Name { get; set; }

    [Required]
    [Column("email")]
    [StringLength(256)]
    [Unicode(false)]
    public string Email { get; set; }

    [Required]
    [Column("password")]
    [StringLength(100)]
    [Unicode(false)]
    public string Password { get; set; }

    [Column("phone")]
    [StringLength(40)]
    [Unicode(false)]
    public string Phone { get; set; }

    [Required]
    [Column("status")]
    [StringLength(20)]
    [Unicode(false)]
    public string Status { get; set; }

    [Column("resetPasswordConfirmCode")]
    [StringLength(50)]
    [Unicode(false)]
    public string ResetPasswordConfirmCode { get; set; }

    [Column("resetPasswordConfirmCodeExpiresAt", TypeName = "datetime")]
    public DateTime? ResetPasswordConfirmCodeExpiresAt { get; set; }

    [Column("createdAt", TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [Column("updatedAt", TypeName = "datetime")]
    public DateTime UpdatedAt { get; set; }

    [Column("lastLoginAt", TypeName = "datetime")]
    public DateTime? LastLoginAt { get; set; }

    [InverseProperty("User")]
    public virtual ICollection<AdminUsersRole> AdminUsersRoles { get; set; } = new List<AdminUsersRole>();
}