// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Team1.VitalBridge.BackStage.Models.EFModels;

public partial class AdminUsersRole
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("roleId")]
    public int RoleId { get; set; }

    [Column("userId")]
    public int UserId { get; set; }

    [Column("createdAt", TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [Column("updatedAt", TypeName = "datetime")]
    public DateTime UpdatedAt { get; set; }

    [ForeignKey("RoleId")]
    [InverseProperty("AdminUsersRoles")]
    public virtual AdminRole Role { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("AdminUsersRoles")]
    public virtual AdminUser User { get; set; }
}