// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Team1.VitalBridge.BackStage.Models.EFModels;

[Index("PermissionCode", Name = "UQ__AdminPer__DF6AE8FFF491A938", IsUnique = true)]
public partial class AdminPermission
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("permissionCode")]
    [StringLength(50)]
    [Unicode(false)]
    public string PermissionCode { get; set; }

    [Required]
    [Column("name")]
    [StringLength(20)]
    [Unicode(false)]
    public string Name { get; set; }

    [Column("info")]
    [StringLength(100)]
    [Unicode(false)]
    public string Info { get; set; }

    [Column("isActive")]
    public bool IsActive { get; set; }

    [Column("createdAt", TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [Column("updatedAt", TypeName = "datetime")]
    public DateTime UpdatedAt { get; set; }

    [Column("deprecatedAt", TypeName = "datetime")]
    public DateTime? DeprecatedAt { get; set; }

    [InverseProperty("Permission")]
    public virtual ICollection<AdminRolePermission> AdminRolePermissions { get; set; } = new List<AdminRolePermission>();
}