// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Team1.VitalBridge.BackStage.Models.EFModels;

[Index("UserId", Name = "UQ__AdminPro__CB9A1CFE2CE53106", IsUnique = true)]
public partial class AdminProfile
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("userId")]
    public int UserId { get; set; }

    [Column("isSuperAdmin")]
    public bool IsSuperAdmin { get; set; }

    [Column("createdByUserId")]
    public int? CreatedByUserId { get; set; }

    [Column("note")]
    [StringLength(500)]
    [Unicode(false)]
    public string Note { get; set; }

    [Column("lastAdminActionAt", TypeName = "datetime")]
    public DateTime? LastAdminActionAt { get; set; }

    [Column("createdAt", TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [Column("updatedAt", TypeName = "datetime")]
    public DateTime UpdatedAt { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("AdminProfile")]
    public virtual User User { get; set; }
}