// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Team1.VitalBridge.BackStage.Models.EFModels;

public partial class AppDbContext : DbContext
{
    public AppDbContext(DbContextOptions<AppDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AdminPermission> AdminPermissions { get; set; }

    public virtual DbSet<AdminRole> AdminRoles { get; set; }

    public virtual DbSet<AdminRolePermission> AdminRolePermissions { get; set; }

    public virtual DbSet<AdminUser> AdminUsers { get; set; }

    public virtual DbSet<AdminUsersRole> AdminUsersRoles { get; set; }

    public virtual DbSet<CareRecipient> CareRecipients { get; set; }

    public virtual DbSet<CareRecipientHealthCondition> CareRecipientHealthConditions { get; set; }

    public virtual DbSet<Cart> Carts { get; set; }

    public virtual DbSet<CartItem> CartItems { get; set; }

    public virtual DbSet<Category> Categories { get; set; }

    public virtual DbSet<City> Citys { get; set; }

    public virtual DbSet<Comment> Comments { get; set; }

    public virtual DbSet<Content> Contents { get; set; }

    public virtual DbSet<ContentCategory> ContentCategories { get; set; }

    public virtual DbSet<Coupon> Coupons { get; set; }

    public virtual DbSet<CouponRecord> CouponRecords { get; set; }

    public virtual DbSet<EmergencyContact> EmergencyContacts { get; set; }

    public virtual DbSet<Event> Events { get; set; }

    public virtual DbSet<EventImage> EventImages { get; set; }

    public virtual DbSet<EventParticipant> EventParticipants { get; set; }

    public virtual DbSet<EventStatus> EventStatuses { get; set; }

    public virtual DbSet<ExternalLogin> ExternalLogins { get; set; }

    public virtual DbSet<Favorite> Favorites { get; set; }

    public virtual DbSet<FeatureService> FeatureServices { get; set; }

    public virtual DbSet<FileStream> FileStreams { get; set; }

    public virtual DbSet<HealthCondition> HealthConditions { get; set; }

    public virtual DbSet<Institution> Institutions { get; set; }

    public virtual DbSet<InstitutionImage> InstitutionImages { get; set; }

    public virtual DbSet<InstitutionPermission> InstitutionPermissions { get; set; }

    public virtual DbSet<InstitutionRole> InstitutionRoles { get; set; }

    public virtual DbSet<InstitutionRolePermission> InstitutionRolePermissions { get; set; }

    public virtual DbSet<InstitutionUser> InstitutionUsers { get; set; }

    public virtual DbSet<InstitutionUserRole> InstitutionUserRoles { get; set; }

    public virtual DbSet<Log> Logs { get; set; }

    public virtual DbSet<LogType> LogTypes { get; set; }

    public virtual DbSet<Media> Medias { get; set; }

    public virtual DbSet<MediaType> MediaTypes { get; set; }

    public virtual DbSet<Notify> Notifys { get; set; }

    public virtual DbSet<NotifyUser> NotifyUsers { get; set; }

    public virtual DbSet<NotifysCategory> NotifysCategories { get; set; }

    public virtual DbSet<Order> Orders { get; set; }

    public virtual DbSet<OrderItem> OrderItems { get; set; }

    public virtual DbSet<OrderRecipent> OrderRecipents { get; set; }

    public virtual DbSet<OrderShipMethod> OrderShipMethods { get; set; }

    public virtual DbSet<OrderStatus> OrderStatuses { get; set; }

    public virtual DbSet<OrederStatusItem> OrederStatusItems { get; set; }

    public virtual DbSet<Organization> Organizations { get; set; }

    public virtual DbSet<OrganizationCertificationRequest> OrganizationCertificationRequests { get; set; }

    public virtual DbSet<OrganizationFeatureService> OrganizationFeatureServices { get; set; }

    public virtual DbSet<OrganizationRoom> OrganizationRooms { get; set; }

    public virtual DbSet<OrganizationServiceTarget> OrganizationServiceTargets { get; set; }

    public virtual DbSet<OrganizationSubsidyInfo> OrganizationSubsidyInfos { get; set; }

    public virtual DbSet<OrganizationType> OrganizationTypes { get; set; }

    public virtual DbSet<Payment> Payments { get; set; }

    public virtual DbSet<PaymentMethod> PaymentMethods { get; set; }

    public virtual DbSet<Permission> Permissions { get; set; }

    public virtual DbSet<Plate> Plates { get; set; }

    public virtual DbSet<PlateImage> PlateImages { get; set; }

    public virtual DbSet<Product> Products { get; set; }

    public virtual DbSet<ProductCategory> ProductCategories { get; set; }

    public virtual DbSet<ProductImage> ProductImages { get; set; }

    public virtual DbSet<ProductNote> ProductNotes { get; set; }

    public virtual DbSet<ProductShip> ProductShips { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<RolePermission> RolePermissions { get; set; }

    public virtual DbSet<RoomType> RoomTypes { get; set; }

    public virtual DbSet<ServiceTarget> ServiceTargets { get; set; }

    public virtual DbSet<Ship> Ships { get; set; }

    public virtual DbSet<ShippingRule> ShippingRules { get; set; }

    public virtual DbSet<ShopHomePageBanner> ShopHomePageBanners { get; set; }

    public virtual DbSet<SubsidyInfo> SubsidyInfos { get; set; }

    public virtual DbSet<Township> Townships { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<UserCareRecipient> UserCareRecipients { get; set; }

    public virtual DbSet<UserRole> UserRoles { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AdminPermission>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__AdminPer__3213E83FD83E5391");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<AdminRole>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__AdminRol__3213E83F79C74AFB");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<AdminRolePermission>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__AdminRol__3213E83FE85C1ED1");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Permission).WithMany(p => p.AdminRolePermissions).HasConstraintName("FK__AdminRole__permi__1E3A7A34");

            entity.HasOne(d => d.Role).WithMany(p => p.AdminRolePermissions).HasConstraintName("FK__AdminRole__updat__1D4655FB");
        });

        modelBuilder.Entity<AdminUser>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__AdminUse__3213E83F4410B5C1");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<AdminUsersRole>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__AdminUse__3213E83FC27BF3BF");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Role).WithMany(p => p.AdminUsersRoles).HasConstraintName("FK__AdminUser__updat__178D7CA5");

            entity.HasOne(d => d.User).WithMany(p => p.AdminUsersRoles).HasConstraintName("FK__AdminUser__userI__1881A0DE");
        });

        modelBuilder.Entity<CareRecipient>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__CareReci__3213E83F283E1834");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.City).WithMany(p => p.CareRecipients).HasConstraintName("FK__CareRecip__cityI__27F8EE98");

            entity.HasOne(d => d.Township).WithMany(p => p.CareRecipients)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FK__CareRecip__towns__28ED12D1");
        });

        modelBuilder.Entity<CareRecipientHealthCondition>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__CareReci__3213E83F527DE103");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.CareRecipient).WithMany(p => p.CareRecipientHealthConditions).HasConstraintName("FK__CareRecip__careR__6225902D");

            entity.HasOne(d => d.HealthConditions).WithMany(p => p.CareRecipientHealthConditions).HasConstraintName("FK__CareRecip__healt__6319B466");
        });

        modelBuilder.Entity<Cart>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Carts__3213E83FB41C7A47");

            entity.Property(e => e.CreateAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Customer).WithOne(p => p.Cart)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Carts__customerI__25518C17");
        });

        modelBuilder.Entity<CartItem>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__CartItem__3213E83FD0E06F6B");

            entity.Property(e => e.AddAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Cart).WithMany(p => p.CartItems)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__CartItems__cartI__30C33EC3");

            entity.HasOne(d => d.Product).WithMany(p => p.CartItems)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__CartItems__produ__2FCF1A8A");
        });

        modelBuilder.Entity<Category>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Categori__3213E83F8B475D9E");

            entity.ToTable(tb => tb.HasTrigger("TR_Categories_ParentChildActiveSync"));

            entity.HasOne(d => d.Father).WithMany(p => p.InverseFather).HasConstraintName("FK__Categorie__fathe__3493CFA7");
        });

        modelBuilder.Entity<City>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Citys__3213E83FE31D8705");
        });

        modelBuilder.Entity<Comment>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Comments__3213E83FAA80E465");

            entity.HasOne(d => d.ContentNavigation).WithMany(p => p.Comments)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Comments__conten__7E37BEF6");

            entity.HasOne(d => d.ParentComment).WithMany(p => p.InverseParentComment).HasConstraintName("FK__Comments__parent__7D439ABD");
        });

        modelBuilder.Entity<Content>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Contents__3213E83F15F6D77F");

            entity.HasOne(d => d.ContentCategory).WithMany(p => p.Contents)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Contents__conten__75A278F5");
        });

        modelBuilder.Entity<ContentCategory>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__ContentC__3213E83FA257F94C");

            entity.HasOne(d => d.ParentCategory).WithMany(p => p.InverseParentCategory).HasConstraintName("FK__ContentCa__paren__72C60C4A");
        });

        modelBuilder.Entity<Coupon>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Coupons__3213E83F754B01B2");

            entity.Property(e => e.CanUseCount).HasDefaultValue(1);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.UsedCount).HasDefaultValue(0);
        });

        modelBuilder.Entity<CouponRecord>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__CouponRe__3213E83F5E799998");

            entity.Property(e => e.CeatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Coupoun).WithMany(p => p.CouponRecords)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__CouponRec__coupo__73852659");

            entity.HasOne(d => d.Customer).WithMany(p => p.CouponRecords)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__CouponRec__custo__72910220");

            entity.HasOne(d => d.Order).WithOne(p => p.CouponRecord)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__CouponRec__order__74794A92");
        });

        modelBuilder.Entity<EmergencyContact>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Emergenc__3213E83FC9C37B22");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.CareRecipient).WithMany(p => p.EmergencyContacts).HasConstraintName("FK__Emergency__updat__68D28DBC");

            entity.HasOne(d => d.City).WithMany(p => p.EmergencyContacts).HasConstraintName("FK__Emergency__cityI__6ABAD62E");

            entity.HasOne(d => d.Township).WithMany(p => p.EmergencyContacts)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FK__Emergency__towns__6BAEFA67");

            entity.HasOne(d => d.User).WithMany(p => p.EmergencyContacts)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FK__Emergency__userI__69C6B1F5");
        });

        modelBuilder.Entity<Event>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Events__3213E83FFC364B27");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Status).WithMany(p => p.Events)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Events__statusId__753864A1");

            entity.HasOne(d => d.Township).WithMany(p => p.Events)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FK__Events__updatedA__74444068");
        });

        modelBuilder.Entity<EventImage>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__EventIma__3213E83F669524BD");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Event).WithMany(p => p.EventImages).HasConstraintName("FK__EventImag__event__7908F585");
        });

        modelBuilder.Entity<EventParticipant>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__EventPar__3213E83FF31227A9");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Event).WithMany(p => p.EventParticipants).HasConstraintName("FK__EventPart__event__7EC1CEDB");

            entity.HasOne(d => d.User).WithMany(p => p.EventParticipants).HasConstraintName("FK__EventPart__updat__7DCDAAA2");
        });

        modelBuilder.Entity<EventStatus>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__EventSta__3213E83F466A3E57");
        });

        modelBuilder.Entity<ExternalLogin>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__External__3213E83F03E4F0C2");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.User).WithMany(p => p.ExternalLogins).HasConstraintName("FK__ExternalL__updat__038683F8");
        });

        modelBuilder.Entity<Favorite>(entity =>
        {
            entity.HasKey(e => new { e.CustomerId, e.ProductId }).HasName("PK__Favorite__04C0C66BB0C1558D");

            entity.Property(e => e.FavoritedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Customer).WithMany(p => p.Favorites)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Favorites__custo__3864608B");

            entity.HasOne(d => d.Product).WithMany(p => p.Favorites)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Favorites__produ__395884C4");
        });

        modelBuilder.Entity<FeatureService>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__FeatureS__3213E83FA8103CEC");

            entity.HasOne(d => d.File).WithMany(p => p.FeatureServices).HasConstraintName("FK__FeatureSe__FileI__01142BA1");
        });

        modelBuilder.Entity<FileStream>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__FileStre__3213E83F7B85532D");
        });

        modelBuilder.Entity<HealthCondition>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__HealthCo__3213E83FC2A2B056");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<Institution>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Institut__3213E83FFBB5B6F4");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.City).WithMany(p => p.Institutions)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Instituti__cityI__43A1090D");

            entity.HasOne(d => d.Township).WithMany(p => p.Institutions)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Instituti__towns__44952D46");
        });

        modelBuilder.Entity<InstitutionImage>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Institut__3213E83FF295EB8A");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Institution).WithMany(p => p.InstitutionImages).HasConstraintName("FK__Instituti__insti__5A846E65");
        });

        modelBuilder.Entity<InstitutionPermission>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Institut__3213E83F233580BA");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<InstitutionRole>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Institut__3213E83F1C7D8FFC");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<InstitutionRolePermission>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Institut__3213E83FD173B977");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Permission).WithMany(p => p.InstitutionRolePermissions).HasConstraintName("FK__Instituti__permi__50FB042B");

            entity.HasOne(d => d.Role).WithMany(p => p.InstitutionRolePermissions).HasConstraintName("FK__Instituti__updat__5006DFF2");
        });

        modelBuilder.Entity<InstitutionUser>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Institut__3213E83F9AB0E44F");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Institution).WithMany(p => p.InstitutionUsers).HasConstraintName("FK__Instituti__insti__4B422AD5");
        });

        modelBuilder.Entity<InstitutionUserRole>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Institut__3213E83F8A5E4D13");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Role).WithMany(p => p.InstitutionUserRoles).HasConstraintName("FK__Instituti__updat__55BFB948");

            entity.HasOne(d => d.User).WithMany(p => p.InstitutionUserRoles).HasConstraintName("FK__Instituti__userI__56B3DD81");
        });

        modelBuilder.Entity<Log>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Logs__3213E83F2A11192F");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Type).WithMany(p => p.Logs).HasConstraintName("FK__Logs__typeId__22FF2F51");

            entity.HasOne(d => d.User).WithMany(p => p.Logs).HasConstraintName("FK__Logs__userId__220B0B18");
        });

        modelBuilder.Entity<LogType>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__LogTypes__3213E83FD92CA96D");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<Media>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Medias__3213E83FDC28E16F");

            entity.HasOne(d => d.Content).WithMany(p => p.Media).HasConstraintName("FK__Medias__contentI__787EE5A0");

            entity.HasOne(d => d.File).WithMany(p => p.Media)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Medias__FileId__7A672E12");

            entity.HasOne(d => d.MediaType).WithMany(p => p.Media)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Medias__mediaTyp__797309D9");
        });

        modelBuilder.Entity<MediaType>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__MediaTyp__3213E83FD58D7346");
        });

        modelBuilder.Entity<Notify>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Notifys__3213E83F748BC455");

            entity.HasOne(d => d.Categories).WithMany(p => p.Notifies)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Notifys__categor__534D60F1");
        });

        modelBuilder.Entity<NotifyUser>(entity =>
        {
            entity.HasKey(e => new { e.NotifyId, e.UserId }).HasName("PK__NotifyUs__56C75409BCA2551A");

            entity.HasOne(d => d.Notify).WithMany(p => p.NotifyUsers).HasConstraintName("FK__NotifyUse__notif__656C112C");

            entity.HasOne(d => d.User).WithMany(p => p.NotifyUsers).HasConstraintName("FK__NotifyUse__userI__6477ECF3");
        });

        modelBuilder.Entity<NotifysCategory>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__NotifysC__3213E83FE7D0DFE2");

            entity.Property(e => e.Enable).HasDefaultValue(true);
        });

        modelBuilder.Entity<Order>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Orders__3213E83FEE1B8F50");

            entity.ToTable(tb => tb.HasTrigger("TR_Orders_UpdateAt"));

            entity.Property(e => e.CouponDiscount).HasDefaultValue(0m);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Coupon).WithMany(p => p.Orders).HasConstraintName("FK__Orders__couponId__6BE40491");

            entity.HasOne(d => d.Customer).WithMany(p => p.Orders)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Orders__customer__69FBBC1F");
        });

        modelBuilder.Entity<OrderItem>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__OrderIte__3213E83F75FE4046");

            entity.HasOne(d => d.Order).WithMany(p => p.OrderItems)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__OrderItem__order__7849DB76");

            entity.HasOne(d => d.Product).WithMany(p => p.OrderItems)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__OrderItem__produ__793DFFAF");
        });

        modelBuilder.Entity<OrderRecipent>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__OrderRec__3213E83FD93DACB1");

            entity.HasOne(d => d.Order).WithOne(p => p.OrderRecipent)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__OrderReci__order__7D0E9093");
        });

        modelBuilder.Entity<OrderShipMethod>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__OrderShi__3213E83F37E12CB6");

            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.City).WithMany(p => p.OrderShipMethods).HasConstraintName("FK__OrderShip__cityI__0697FACD");

            entity.HasOne(d => d.Order).WithOne(p => p.OrderShipMethod)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__OrderShip__order__04AFB25B");

            entity.HasOne(d => d.Ship).WithMany(p => p.OrderShipMethods)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__OrderShip__shipI__05A3D694");

            entity.HasOne(d => d.Township).WithMany(p => p.OrderShipMethods).HasConstraintName("FK__OrderShip__towns__078C1F06");
        });

        modelBuilder.Entity<OrderStatus>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__OrderSta__3213E83F25D28A0C");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Order).WithMany(p => p.OrderStatuses)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__OrderStat__order__7FEAFD3E");
        });

        modelBuilder.Entity<OrederStatusItem>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__OrederSt__3213E83F77F613D0");
        });

        modelBuilder.Entity<Organization>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Organiza__3213E83FD65F9CA6");

            entity.Property(e => e.IsActive).HasDefaultValue(true);

            entity.HasOne(d => d.City).WithMany(p => p.Organizations)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Organizat__cityI__0B91BA14");

            entity.HasOne(d => d.District).WithMany(p => p.Organizations)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Organizat__distr__0C85DE4D");

            entity.HasOne(d => d.Type).WithMany(p => p.Organizations)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Organizat__typeI__0D7A0286");
            entity.HasOne(d => d.Institution) 
                .WithMany(p => p.Organizations)
                .HasForeignKey(d => d.institutionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Organizations_Institutions");
                });

        modelBuilder.Entity<OrganizationCertificationRequest>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Organiza__3213E83FEACB9B80");

            entity.HasOne(d => d.Organization).WithMany(p => p.OrganizationCertificationRequests)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Organizat__organ__160F4887");
        });

        modelBuilder.Entity<OrganizationFeatureService>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Organiza__3213E83F5B942C67");

            entity.HasOne(d => d.FeatureService).WithMany(p => p.OrganizationFeatureServices)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Organizat__featu__19DFD96B");

            entity.HasOne(d => d.Organization).WithMany(p => p.OrganizationFeatureServices)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Organizat__organ__18EBB532");
        });

        modelBuilder.Entity<OrganizationRoom>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Organiza__3213E83F1F6D0B39");

            entity.HasOne(d => d.Organization).WithMany(p => p.OrganizationRooms).HasConstraintName("FK__Organizat__organ__1CBC4616");

            entity.HasOne(d => d.RoomType).WithMany(p => p.OrganizationRooms).HasConstraintName("FK__Organizat__roomT__1DB06A4F");
        });

        modelBuilder.Entity<OrganizationServiceTarget>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Organiza__3213E83F1185B39E");

            entity.HasOne(d => d.Organization).WithMany(p => p.OrganizationServiceTargets)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Organizat__organ__208CD6FA");

            entity.HasOne(d => d.ServiceTarget).WithMany(p => p.OrganizationServiceTargets)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Organizat__servi__2180FB33");
        });

        modelBuilder.Entity<OrganizationSubsidyInfo>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Organiza__3213E83F11FC8A66");

            entity.HasOne(d => d.Organization).WithMany(p => p.OrganizationSubsidyInfos)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Organizat__organ__123EB7A3");

            entity.HasOne(d => d.SubsidyInfo).WithMany(p => p.OrganizationSubsidyInfos)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Organizat__subsi__1332DBDC");
        });

        modelBuilder.Entity<OrganizationType>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Organiza__3213E83F1A530197");
        });

        modelBuilder.Entity<Payment>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Payment__3213E83F2A0DC017");

            entity.ToTable("Payment", tb => tb.HasTrigger("TR_Payment_UpdateAt"));

            entity.Property(e => e.CreatAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Order).WithOne(p => p.Payment)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Payment__orderId__0C50D423");

            entity.HasOne(d => d.PayMethod).WithMany(p => p.Payments)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Payment__payMeth__0D44F85C");
        });

        modelBuilder.Entity<PaymentMethod>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__PaymentM__3213E83F4E3F1D36");

            entity.Property(e => e.IsActive).HasDefaultValue(true);
        });

        modelBuilder.Entity<Permission>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Permissi__3213E83F04E485B3");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<Plate>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Plate__3213E83F49303613");

            entity.Property(e => e.Enable).HasDefaultValue(true);

            entity.HasOne(d => d.DefaultImageFile).WithMany(p => p.Plates)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Plate__defaultIm__693CA210");
        });

        modelBuilder.Entity<PlateImage>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__PlateIma__3213E83F85FFE3F6");

            entity.HasOne(d => d.ImageFile).WithMany(p => p.PlateImages).HasConstraintName("FK__PlateImag__image__6C190EBB");

            entity.HasOne(d => d.Plate).WithMany(p => p.PlateImages).HasConstraintName("FK__PlateImag__plate__6D0D32F4");
        });

        modelBuilder.Entity<Product>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Products__3213E83F9EE05866");

            entity.ToTable(tb => tb.HasTrigger("TR_products_UpdateAt"));

            entity.Property(e => e.CreateAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.UpdateAt).HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<ProductCategory>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__ProductC__3213E83F585215F0");

            entity.HasOne(d => d.Category).WithMany(p => p.ProductCategories)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ProductCa__categ__55F4C372");

            entity.HasOne(d => d.Product).WithMany(p => p.ProductCategories)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ProductCa__produ__55009F39");
        });

        modelBuilder.Entity<ProductImage>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__ProductI__3213E83F22475167");

            entity.Property(e => e.SortOrder).HasDefaultValue(2);

            entity.HasOne(d => d.Product).WithMany(p => p.ProductImages)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ProductIm__produ__58D1301D");
        });

        modelBuilder.Entity<ProductNote>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__ProductN__3213E83F372D26E7");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<ProductShip>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__ProductS__3213E83FD375B1F3");

            entity.HasOne(d => d.Product).WithMany(p => p.ProductShips)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ProductSh__produ__4F47C5E3");

            entity.HasOne(d => d.Ship).WithMany(p => p.ProductShips)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ProductSh__shipI__503BEA1C");
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Roles__3213E83F4204A1A3");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<RolePermission>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__RolePerm__3213E83FDB279E52");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Permission).WithMany(p => p.RolePermissions).HasConstraintName("FK__RolePermi__permi__22401542");

            entity.HasOne(d => d.Role).WithMany(p => p.RolePermissions).HasConstraintName("FK__RolePermi__roleI__214BF109");
        });

        modelBuilder.Entity<RoomType>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__RoomType__3213E83F72DA8649");
        });

        modelBuilder.Entity<ServiceTarget>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__ServiceT__3213E83FB2B54919");
        });

        modelBuilder.Entity<Ship>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Ships__3213E83F48BF2108");

            entity.Property(e => e.IsActive).HasDefaultValue(true);
        });

        modelBuilder.Entity<ShippingRule>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Shipping__3213E83FB58663E0");

            entity.ToTable(tb => tb.HasTrigger("TR_ShippingRules_UpdateAt"));

            entity.Property(e => e.CreateAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<ShopHomePageBanner>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__ShopHome__3213E83FE85425F3");

            entity.ToTable(tb => tb.HasTrigger("trg_ShopHomePageBanners_Updated"));

            entity.Property(e => e.CreateAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.Updated).HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<SubsidyInfo>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__SubsidyI__3213E83FCD950DF0");
        });

        modelBuilder.Entity<Township>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Township__3213E83F59038B3F");

            entity.HasOne(d => d.City).WithMany(p => p.Townships).HasConstraintName("FK__Townships__cityI__59063A47");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Users__3213E83F7F871FD6");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.City).WithMany(p => p.Users).HasConstraintName("FK__Users__cityId__5FB337D6");

            entity.HasOne(d => d.Township).WithMany(p => p.Users)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FK__Users__townshipI__60A75C0F");
        });

        modelBuilder.Entity<UserCareRecipient>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__UserCare__3213E83F0D47C632");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.CareRecipient).WithMany(p => p.UserCareRecipients).HasConstraintName("FK__UserCareR__careR__2DB1C7EE");

            entity.HasOne(d => d.User).WithMany(p => p.UserCareRecipients).HasConstraintName("FK__UserCareR__userI__2CBDA3B5");
        });

        modelBuilder.Entity<UserRole>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__UserRole__3213E83F8A31913F");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Role).WithMany(p => p.UserRoles).HasConstraintName("FK__UserRoles__updat__32767D0B");

            entity.HasOne(d => d.User).WithMany(p => p.UserRoles).HasConstraintName("FK__UserRoles__userI__336AA144");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}