// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Team1.VitalBridge.BackStage.Models.ViewModels;

namespace Team1.VitalBridge.BackStage.Models.EFModels;

public partial class AppDbContext : DbContext
{
    public AppDbContext(DbContextOptions<AppDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AdminPermission> AdminPermissions { get; set; }

    public virtual DbSet<AdminRole> AdminRoles { get; set; }

    public virtual DbSet<AdminRolePermission> AdminRolePermissions { get; set; }

    public virtual DbSet<AdminUser> AdminUsers { get; set; }

    public virtual DbSet<AdminUsersRole> AdminUsersRoles { get; set; }

    public virtual DbSet<CareRecipient> CareRecipients { get; set; }

    public virtual DbSet<CareRecipientHealthCondition> CareRecipientHealthConditions { get; set; }

    public virtual DbSet<Cart> Carts { get; set; }

    public virtual DbSet<CartItem> CartItems { get; set; }

    public virtual DbSet<Category> Categories { get; set; }

    public virtual DbSet<City> Citys { get; set; }

    public virtual DbSet<Comment> Comments { get; set; }

    public virtual DbSet<Content> Contents { get; set; }

    public virtual DbSet<ContentCategory> ContentCategories { get; set; }

    public virtual DbSet<ContentType> ContentTypes { get; set; }

    public virtual DbSet<ContentTypeCategoryPair> ContentTypeCategoryPairs { get; set; }

    public virtual DbSet<Coupon> Coupons { get; set; }

    public virtual DbSet<CouponRecord> CouponRecords { get; set; }

    public virtual DbSet<EmergencyContact> EmergencyContacts { get; set; }

    public virtual DbSet<Event> Events { get; set; }

    public virtual DbSet<EventImage> EventImages { get; set; }

    public virtual DbSet<EventParticipant> EventParticipants { get; set; }

    public virtual DbSet<EventStatus> EventStatuses { get; set; }

    public virtual DbSet<ExternalLogin> ExternalLogins { get; set; }

    public virtual DbSet<Favorite> Favorites { get; set; }

    public virtual DbSet<FeatureService> FeatureServices { get; set; }

    public virtual DbSet<FileStream> FileStreams { get; set; }

    public virtual DbSet<HealthCondition> HealthConditions { get; set; }

    public virtual DbSet<Institution> Institutions { get; set; }

    public virtual DbSet<InstitutionImage> InstitutionImages { get; set; }

    public virtual DbSet<InstitutionPermission> InstitutionPermissions { get; set; }

    public virtual DbSet<InstitutionRole> InstitutionRoles { get; set; }

    public virtual DbSet<InstitutionRolePermission> InstitutionRolePermissions { get; set; }

    public virtual DbSet<InstitutionUser> InstitutionUsers { get; set; }

    public virtual DbSet<InstitutionUserRole> InstitutionUserRoles { get; set; }

    public virtual DbSet<Log> Logs { get; set; }

    public virtual DbSet<LogType> LogTypes { get; set; }

    public virtual DbSet<Media> Medias { get; set; }

    public virtual DbSet<MediaType> MediaTypes { get; set; }

    public virtual DbSet<Notify> Notifys { get; set; }

    public virtual DbSet<NotifyUser> NotifyUsers { get; set; }

    public virtual DbSet<NotifysCategory> NotifysCategories { get; set; }

    public virtual DbSet<Order> Orders { get; set; }

    public virtual DbSet<OrderItem> OrderItems { get; set; }

    public virtual DbSet<OrderRecipent> OrderRecipents { get; set; }

    public virtual DbSet<OrderShipMethod> OrderShipMethods { get; set; }

    public virtual DbSet<OrderStatus> OrderStatuses { get; set; }

    public virtual DbSet<OrederStatusItem> OrederStatusItems { get; set; }

    public virtual DbSet<Organization> Organizations { get; set; }

    public virtual DbSet<OrganizationCertificationRequest> OrganizationCertificationRequests { get; set; }

    public virtual DbSet<OrganizationFeatureService> OrganizationFeatureServices { get; set; }

    public virtual DbSet<OrganizationRoom> OrganizationRooms { get; set; }

    public virtual DbSet<OrganizationServiceTarget> OrganizationServiceTargets { get; set; }

    public virtual DbSet<OrganizationSubsidyInfo> OrganizationSubsidyInfos { get; set; }

    public virtual DbSet<OrganizationType> OrganizationTypes { get; set; }

    public virtual DbSet<Payment> Payments { get; set; }

    public virtual DbSet<PaymentMethod> PaymentMethods { get; set; }

    public virtual DbSet<Permission> Permissions { get; set; }

    public virtual DbSet<Plate> Plates { get; set; }

    public virtual DbSet<PlateImage> PlateImages { get; set; }

    public virtual DbSet<Product> Products { get; set; }

    public virtual DbSet<ProductCategory> ProductCategories { get; set; }

    public virtual DbSet<ProductImage> ProductImages { get; set; }

    public virtual DbSet<ProductNote> ProductNotes { get; set; }

    public virtual DbSet<ProductShip> ProductShips { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<RolePermission> RolePermissions { get; set; }

    public virtual DbSet<RoomType> RoomTypes { get; set; }

    public virtual DbSet<ServiceTarget> ServiceTargets { get; set; }

    public virtual DbSet<Ship> Ships { get; set; }

    public virtual DbSet<ShippingRule> ShippingRules { get; set; }

    public virtual DbSet<ShopHomePageBanner> ShopHomePageBanners { get; set; }

    public virtual DbSet<SubsidyInfo> SubsidyInfos { get; set; }

    public virtual DbSet<Township> Townships { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<UserCareRecipient> UserCareRecipients { get; set; }

    public virtual DbSet<UserRole> UserRoles { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AdminPermission>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__AdminPer__3213E83F30156EC4");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<AdminRole>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__AdminRol__3213E83F8C6DD647");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<AdminRolePermission>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__AdminRol__3213E83F2AE96880");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Permission).WithMany(p => p.AdminRolePermissions).HasConstraintName("FK__AdminRole__permi__220B0B18");

            entity.HasOne(d => d.Role).WithMany(p => p.AdminRolePermissions).HasConstraintName("FK__AdminRole__updat__2116E6DF");
        });

        modelBuilder.Entity<AdminUser>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__AdminUse__3213E83FD6AAA0BC");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<AdminUsersRole>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__AdminUse__3213E83FDF547F99");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Role).WithMany(p => p.AdminUsersRoles).HasConstraintName("FK__AdminUser__updat__1B5E0D89");

            entity.HasOne(d => d.User).WithMany(p => p.AdminUsersRoles).HasConstraintName("FK__AdminUser__userI__1C5231C2");
        });

        modelBuilder.Entity<CareRecipient>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__CareReci__3213E83FE6F288B9");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.City).WithMany(p => p.CareRecipients).HasConstraintName("FK__CareRecip__cityI__2BC97F7C");

            entity.HasOne(d => d.Township).WithMany(p => p.CareRecipients)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FK__CareRecip__towns__2CBDA3B5");
        });

        modelBuilder.Entity<CareRecipientHealthCondition>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__CareReci__3213E83FD7FE9574");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.CareRecipient).WithMany(p => p.CareRecipientHealthConditions).HasConstraintName("FK__CareRecip__careR__65F62111");

            entity.HasOne(d => d.HealthConditions).WithMany(p => p.CareRecipientHealthConditions).HasConstraintName("FK__CareRecip__healt__66EA454A");
        });

        modelBuilder.Entity<Cart>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Carts__3213E83F243DCBC0");

            entity.Property(e => e.CreateAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Customer).WithOne(p => p.Cart)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Carts__customerI__29221CFB");
        });

        modelBuilder.Entity<CartItem>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__CartItem__3213E83F3709E441");

            entity.Property(e => e.AddAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Cart).WithMany(p => p.CartItems)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__CartItems__cartI__3493CFA7");

            entity.HasOne(d => d.Product).WithMany(p => p.CartItems)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__CartItems__produ__339FAB6E");
        });

        modelBuilder.Entity<Category>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Categori__3213E83FBF28C199");

            entity.ToTable(tb => tb.HasTrigger("TR_Categories_ParentChildActiveSync"));

            entity.HasOne(d => d.Father).WithMany(p => p.InverseFather).HasConstraintName("FK__Categorie__fathe__3864608B");
        });

        modelBuilder.Entity<City>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Citys__3213E83F73792AD6");
        });

        modelBuilder.Entity<Comment>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Comments__3213E83FCCD2F9CD");

            entity.HasOne(d => d.ContentNavigation).WithMany(p => p.Comments)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Comments__conten__00200768");

            entity.HasOne(d => d.ParentComment).WithMany(p => p.InverseParentComment).HasConstraintName("FK__Comments__parent__7F2BE32F");
        });

        modelBuilder.Entity<Content>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Contents__3213E83F19E909C1");

            entity.HasOne(d => d.ContentCategory).WithMany(p => p.Contents)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Contents__conten__76969D2E");

            entity.HasOne(d => d.ContentType).WithMany(p => p.Contents)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Contents__conten__778AC167");
        });

        modelBuilder.Entity<ContentCategory>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__ContentC__3213E83F6C8F78BA");

            entity.HasOne(d => d.ParentCategory).WithMany(p => p.InverseParentCategory).HasConstraintName("FK__ContentCa__paren__73BA3083");
        });

        modelBuilder.Entity<ContentType>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__ContentT__3213E83FF24F7494");
        });

        modelBuilder.Entity<ContentTypeCategoryPair>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__ContentT__3213E83F5F5539D0");

            entity.HasOne(d => d.ContentCategory).WithMany(p => p.ContentTypeCategoryPairs)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ContentTy__conte__02FC7413");

            entity.HasOne(d => d.ContentType).WithMany(p => p.ContentTypeCategoryPairs)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ContentTy__conte__03F0984C");
        });

        modelBuilder.Entity<Coupon>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Coupons__3213E83F8873E240");

            entity.Property(e => e.CanUseCount).HasDefaultValue(1);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.UsedCount).HasDefaultValue(0);
        });

        modelBuilder.Entity<CouponRecord>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__CouponRe__3213E83FB7445F7B");

            entity.Property(e => e.CeatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Coupoun).WithMany(p => p.CouponRecords)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__CouponRec__coupo__7755B73D");

            entity.HasOne(d => d.Customer).WithMany(p => p.CouponRecords)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__CouponRec__custo__76619304");

            entity.HasOne(d => d.Order).WithOne(p => p.CouponRecord)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__CouponRec__order__7849DB76");
        });

        modelBuilder.Entity<EmergencyContact>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Emergenc__3213E83F85B28EF2");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.CareRecipient).WithMany(p => p.EmergencyContacts).HasConstraintName("FK__Emergency__updat__6CA31EA0");

            entity.HasOne(d => d.City).WithMany(p => p.EmergencyContacts).HasConstraintName("FK__Emergency__cityI__6E8B6712");

            entity.HasOne(d => d.Township).WithMany(p => p.EmergencyContacts)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FK__Emergency__towns__6F7F8B4B");

            entity.HasOne(d => d.User).WithMany(p => p.EmergencyContacts)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FK__Emergency__userI__6D9742D9");
        });

        modelBuilder.Entity<Event>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Events__3213E83F55C12760");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Status).WithMany(p => p.Events)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Events__statusId__7908F585");

            entity.HasOne(d => d.Township).WithMany(p => p.Events)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FK__Events__updatedA__7814D14C");
        });

        modelBuilder.Entity<EventImage>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__EventIma__3213E83FD4CDD023");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Event).WithMany(p => p.EventImages).HasConstraintName("FK__EventImag__event__7CD98669");
        });

        modelBuilder.Entity<EventParticipant>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__EventPar__3213E83FCD783100");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Event).WithMany(p => p.EventParticipants).HasConstraintName("FK__EventPart__event__02925FBF");

            entity.HasOne(d => d.User).WithMany(p => p.EventParticipants).HasConstraintName("FK__EventPart__updat__019E3B86");
        });

        modelBuilder.Entity<EventStatus>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__EventSta__3213E83F1BFB64AD");
        });

        modelBuilder.Entity<ExternalLogin>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__External__3213E83F6EB6EB9C");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.User).WithMany(p => p.ExternalLogins).HasConstraintName("FK__ExternalL__updat__075714DC");
        });

        modelBuilder.Entity<Favorite>(entity =>
        {
            entity.HasKey(e => new { e.CustomerId, e.ProductId }).HasName("PK__Favorite__04C0C66BDBF18C6F");

            entity.Property(e => e.FavoritedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Customer).WithMany(p => p.Favorites)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Favorites__custo__3C34F16F");

            entity.HasOne(d => d.Product).WithMany(p => p.Favorites)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Favorites__produ__3D2915A8");
        });

        modelBuilder.Entity<FeatureService>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__FeatureS__3213E83F83DD3FA2");

            entity.HasOne(d => d.File).WithMany(p => p.FeatureServices).HasConstraintName("FK__FeatureSe__FileI__06CD04F7");
        });

        modelBuilder.Entity<FileStream>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__FileStre__3213E83F8A3799CB");
        });

        modelBuilder.Entity<HealthCondition>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__HealthCo__3213E83F7B0AD3B4");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<Institution>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Institut__3213E83F180450B6");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.City).WithMany(p => p.Institutions)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Instituti__cityI__477199F1");

            entity.HasOne(d => d.Township).WithMany(p => p.Institutions)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Instituti__towns__4865BE2A");
        });

        modelBuilder.Entity<InstitutionImage>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Institut__3213E83FD5369928");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Institution).WithMany(p => p.InstitutionImages).HasConstraintName("FK__Instituti__insti__5E54FF49");
        });

        modelBuilder.Entity<InstitutionPermission>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Institut__3213E83FD749457D");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<InstitutionRole>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Institut__3213E83F11659245");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<InstitutionRolePermission>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Institut__3213E83FD748C395");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Permission).WithMany(p => p.InstitutionRolePermissions).HasConstraintName("FK__Instituti__permi__54CB950F");

            entity.HasOne(d => d.Role).WithMany(p => p.InstitutionRolePermissions).HasConstraintName("FK__Instituti__updat__53D770D6");
        });

        modelBuilder.Entity<InstitutionUser>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Institut__3213E83F3C0BBC0B");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Institution).WithMany(p => p.InstitutionUsers).HasConstraintName("FK__Instituti__insti__4F12BBB9");
        });

        modelBuilder.Entity<InstitutionUserRole>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Institut__3213E83FB449C5FA");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Role).WithMany(p => p.InstitutionUserRoles).HasConstraintName("FK__Instituti__updat__59904A2C");

            entity.HasOne(d => d.User).WithMany(p => p.InstitutionUserRoles).HasConstraintName("FK__Instituti__userI__5A846E65");
        });

        modelBuilder.Entity<Log>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Logs__3213E83F26EA3C8C");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Type).WithMany(p => p.Logs).HasConstraintName("FK__Logs__typeId__26CFC035");

            entity.HasOne(d => d.User).WithMany(p => p.Logs).HasConstraintName("FK__Logs__userId__25DB9BFC");
        });

        modelBuilder.Entity<LogType>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__LogTypes__3213E83F1D941599");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<Media>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Medias__3213E83F004B3572");

            entity.HasOne(d => d.Content).WithMany(p => p.Media).HasConstraintName("FK__Medias__contentI__7A672E12");

            entity.HasOne(d => d.File).WithMany(p => p.Media)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Medias__FileId__7C4F7684");

            entity.HasOne(d => d.MediaType).WithMany(p => p.Media)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Medias__mediaTyp__7B5B524B");
        });

        modelBuilder.Entity<MediaType>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__MediaTyp__3213E83FA62ED093");
        });

        modelBuilder.Entity<Notify>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Notifys__3213E83F31C5BCEC");

            entity.HasOne(d => d.Categories).WithMany(p => p.Notifies)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Notifys__categor__534D60F1");
        });

        modelBuilder.Entity<NotifyUser>(entity =>
        {
            entity.HasKey(e => new { e.NotifyId, e.UserId }).HasName("PK__NotifyUs__56C754094C15ACB6");

            entity.HasOne(d => d.Notify).WithMany(p => p.NotifyUsers).HasConstraintName("FK__NotifyUse__notif__656C112C");

            entity.HasOne(d => d.User).WithMany(p => p.NotifyUsers).HasConstraintName("FK__NotifyUse__userI__6477ECF3");
        });

        modelBuilder.Entity<NotifysCategory>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__NotifysC__3213E83F30FDCDE6");

            entity.Property(e => e.Enable).HasDefaultValue(true);
        });

        modelBuilder.Entity<Order>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Orders__3213E83FB8E1B2A9");

            entity.ToTable(tb => tb.HasTrigger("TR_Orders_UpdateAt"));

            entity.Property(e => e.CouponDiscount).HasDefaultValue(0m);
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Coupon).WithMany(p => p.Orders).HasConstraintName("FK__Orders__couponId__6FB49575");

            entity.HasOne(d => d.Customer).WithMany(p => p.Orders)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Orders__customer__6DCC4D03");
        });

        modelBuilder.Entity<OrderItem>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__OrderIte__3213E83FD1EA2FF5");

            entity.HasOne(d => d.Order).WithMany(p => p.OrderItems)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__OrderItem__order__7C1A6C5A");

            entity.HasOne(d => d.Product).WithMany(p => p.OrderItems)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__OrderItem__produ__7D0E9093");
        });

        modelBuilder.Entity<OrderRecipent>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__OrderRec__3213E83F46EB9898");

            entity.HasOne(d => d.Order).WithOne(p => p.OrderRecipent)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__OrderReci__order__00DF2177");
        });

        modelBuilder.Entity<OrderShipMethod>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__OrderShi__3213E83F1F1A0463");

            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.City).WithMany(p => p.OrderShipMethods).HasConstraintName("FK__OrderShip__cityI__0A688BB1");

            entity.HasOne(d => d.Order).WithOne(p => p.OrderShipMethod)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__OrderShip__order__0880433F");

            entity.HasOne(d => d.Ship).WithMany(p => p.OrderShipMethods)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__OrderShip__shipI__09746778");

            entity.HasOne(d => d.Township).WithMany(p => p.OrderShipMethods).HasConstraintName("FK__OrderShip__towns__0B5CAFEA");
        });

        modelBuilder.Entity<OrderStatus>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__OrderSta__3213E83F3174D7F0");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Order).WithMany(p => p.OrderStatuses)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__OrderStat__order__03BB8E22");
        });

        modelBuilder.Entity<OrederStatusItem>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__OrederSt__3213E83FB3D88360");
        });

        modelBuilder.Entity<Organization>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Organiza__3213E83FBC1C46BD");

            entity.HasOne(d => d.City).WithMany(p => p.Organizations)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Organizat__cityI__114A936A");

            entity.HasOne(d => d.District).WithMany(p => p.Organizations)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Organizat__distr__123EB7A3");

            entity.HasOne(d => d.Type).WithMany(p => p.Organizations)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Organizat__typeI__1332DBDC");
        });

        modelBuilder.Entity<OrganizationCertificationRequest>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Organiza__3213E83F17A9D1B1");

            entity.HasOne(d => d.Organization).WithMany(p => p.OrganizationCertificationRequests)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Organizat__organ__19DFD96B");
        });

        modelBuilder.Entity<OrganizationFeatureService>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Organiza__3213E83FB1DE9D00");

            entity.HasOne(d => d.FeatureService).WithMany(p => p.OrganizationFeatureServices)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Organizat__featu__1DB06A4F");

            entity.HasOne(d => d.Organization).WithMany(p => p.OrganizationFeatureServices)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Organizat__organ__1CBC4616");
        });

        modelBuilder.Entity<OrganizationRoom>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Organiza__3213E83FA66925C7");

            entity.HasOne(d => d.Organization).WithMany(p => p.OrganizationRooms).HasConstraintName("FK__Organizat__organ__208CD6FA");

            entity.HasOne(d => d.RoomType).WithMany(p => p.OrganizationRooms).HasConstraintName("FK__Organizat__roomT__2180FB33");
        });

        modelBuilder.Entity<OrganizationServiceTarget>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Organiza__3213E83FD65FD26B");

            entity.HasOne(d => d.Organization).WithMany(p => p.OrganizationServiceTargets)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Organizat__organ__245D67DE");

            entity.HasOne(d => d.ServiceTarget).WithMany(p => p.OrganizationServiceTargets)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Organizat__servi__25518C17");
        });

        modelBuilder.Entity<OrganizationSubsidyInfo>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Organiza__3213E83F09A12BF3");

            entity.HasOne(d => d.Organization).WithMany(p => p.OrganizationSubsidyInfos)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Organizat__organ__160F4887");

            entity.HasOne(d => d.SubsidyInfo).WithMany(p => p.OrganizationSubsidyInfos)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Organizat__subsi__17036CC0");
        });

        modelBuilder.Entity<OrganizationType>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Organiza__3213E83F01E74461");
        });

        modelBuilder.Entity<Payment>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Payment__3213E83FF4033906");

            entity.ToTable("Payment", tb => tb.HasTrigger("TR_Payment_UpdateAt"));

            entity.Property(e => e.CreatAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Order).WithOne(p => p.Payment)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Payment__orderId__10216507");

            entity.HasOne(d => d.PayMethod).WithMany(p => p.Payments)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Payment__payMeth__11158940");
        });

        modelBuilder.Entity<PaymentMethod>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__PaymentM__3213E83F79861ADB");

            entity.Property(e => e.IsActive).HasDefaultValue(true);
        });

        modelBuilder.Entity<Permission>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Permissi__3213E83FA45A61CF");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<Plate>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Plate__3213E83FB589359C");

            entity.Property(e => e.Enable).HasDefaultValue(true);

            entity.HasOne(d => d.DefaultImageFile).WithMany(p => p.Plates)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Plate__defaultIm__693CA210");
        });

        modelBuilder.Entity<PlateImage>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__PlateIma__3213E83FC5260051");

            entity.HasOne(d => d.ImageFile).WithMany(p => p.PlateImages).HasConstraintName("FK__PlateImag__image__6C190EBB");

            entity.HasOne(d => d.Plate).WithMany(p => p.PlateImages).HasConstraintName("FK__PlateImag__plate__6D0D32F4");
        });

        modelBuilder.Entity<Product>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Products__3213E83F3E0645F6");

            entity.ToTable(tb => tb.HasTrigger("TR_products_UpdateAt"));

            entity.Property(e => e.CreateAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.UpdateAt).HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<ProductCategory>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__ProductC__3213E83F2ADBBEB9");

            entity.HasOne(d => d.Category).WithMany(p => p.ProductCategories)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ProductCa__categ__59C55456");

            entity.HasOne(d => d.Product).WithMany(p => p.ProductCategories)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ProductCa__produ__58D1301D");
        });

        modelBuilder.Entity<ProductImage>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__ProductI__3213E83F325CBA26");

            entity.Property(e => e.SortOrder).HasDefaultValue(2);

            entity.HasOne(d => d.Product).WithMany(p => p.ProductImages)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ProductIm__produ__5CA1C101");
        });

        modelBuilder.Entity<ProductNote>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__ProductN__3213E83F402925B3");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<ProductShip>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__ProductS__3213E83FE97AF470");

            entity.HasOne(d => d.Product).WithMany(p => p.ProductShips)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ProductSh__produ__531856C7");

            entity.HasOne(d => d.Ship).WithMany(p => p.ProductShips)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ProductSh__shipI__540C7B00");
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Roles__3213E83FADF078F0");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<RolePermission>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__RolePerm__3213E83FF1A06F3D");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Permission).WithMany(p => p.RolePermissions).HasConstraintName("FK__RolePermi__permi__2610A626");

            entity.HasOne(d => d.Role).WithMany(p => p.RolePermissions).HasConstraintName("FK__RolePermi__roleI__251C81ED");
        });

        modelBuilder.Entity<RoomType>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__RoomType__3213E83FB405BD21");
        });

        modelBuilder.Entity<ServiceTarget>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__ServiceT__3213E83FA594B66D");
        });

        modelBuilder.Entity<Ship>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Ships__3213E83F5DBAEAD9");

            entity.Property(e => e.IsActive).HasDefaultValue(true);
        });

        modelBuilder.Entity<ShippingRule>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Shipping__3213E83F94210E32");

            entity.ToTable(tb => tb.HasTrigger("TR_ShippingRules_UpdateAt"));

            entity.Property(e => e.CreateAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<ShopHomePageBanner>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__ShopHome__3213E83F4E7F559D");

            entity.ToTable(tb => tb.HasTrigger("trg_ShopHomePageBanners_Updated"));

            entity.Property(e => e.CreateAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.Updated).HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<SubsidyInfo>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__SubsidyI__3213E83FBF75FAD0");
        });

        modelBuilder.Entity<Township>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Township__3213E83FEBF5813F");

            entity.HasOne(d => d.City).WithMany(p => p.Townships).HasConstraintName("FK__Townships__cityI__59063A47");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Users__3213E83FC09AD4A7");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.City).WithMany(p => p.Users).HasConstraintName("FK__Users__cityId__5FB337D6");

            entity.HasOne(d => d.Township).WithMany(p => p.Users)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FK__Users__townshipI__60A75C0F");
        });

        modelBuilder.Entity<UserCareRecipient>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__UserCare__3213E83FF6C9B3A1");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.CareRecipient).WithMany(p => p.UserCareRecipients).HasConstraintName("FK__UserCareR__careR__318258D2");

            entity.HasOne(d => d.User).WithMany(p => p.UserCareRecipients).HasConstraintName("FK__UserCareR__userI__308E3499");
        });

        modelBuilder.Entity<UserRole>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__UserRole__3213E83FC937B0DC");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Role).WithMany(p => p.UserRoles).HasConstraintName("FK__UserRoles__updat__36470DEF");

            entity.HasOne(d => d.User).WithMany(p => p.UserRoles).HasConstraintName("FK__UserRoles__userI__373B3228");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);

public DbSet<Team1.VitalBridge.BackStage.Models.ViewModels.ContentTypeCategoryPairDisplayViewModel> ContentTypeCategoryPairDisplayViewModel { get; set; } = default!;
}