// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Team1.VitalBridge.BackStage.Models.EFModels;

[Index("CareRecipientId", Name = "UQ__CareReci__ED1D48978B884464", IsUnique = true)]
public partial class CareRecipient
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("careRecipientId")]
    [StringLength(50)]
    [Unicode(false)]
    public string CareRecipientId { get; set; }

    [Required]
    [Column("name")]
    [StringLength(20)]
    [Unicode(false)]
    public string Name { get; set; }

    [Required]
    [Column("gender")]
    [StringLength(5)]
    [Unicode(false)]
    public string Gender { get; set; }

    [Column("birthDate")]
    public DateOnly BirthDate { get; set; }

    [Column("height")]
    public int Height { get; set; }

    [Column("weight")]
    public int Weight { get; set; }

    [Required]
    [Column("phone")]
    [StringLength(10)]
    [Unicode(false)]
    public string Phone { get; set; }

    [Column("photoUrl")]
    [StringLength(256)]
    [Unicode(false)]
    public string PhotoUrl { get; set; }

    [Column("photoInfo")]
    [StringLength(50)]
    [Unicode(false)]
    public string PhotoInfo { get; set; }

    [Column("cityId")]
    public int? CityId { get; set; }

    [Column("townshipId")]
    public int? TownshipId { get; set; }

    [Column("address")]
    [StringLength(100)]
    [Unicode(false)]
    public string Address { get; set; }

    [Column("confirmCode")]
    [StringLength(50)]
    [Unicode(false)]
    public string ConfirmCode { get; set; }

    [Column("careLevel")]
    public int CareLevel { get; set; }

    [Column("isActive")]
    public bool IsActive { get; set; }

    [Column("confirmCodeExpiresAt", TypeName = "datetime")]
    public DateTime? ConfirmCodeExpiresAt { get; set; }

    [Column("createdAt", TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [Column("updatedAt", TypeName = "datetime")]
    public DateTime UpdatedAt { get; set; }

    [InverseProperty("CareRecipient")]
    public virtual ICollection<CareRecipientHealthCondition> CareRecipientHealthConditions { get; set; } = new List<CareRecipientHealthCondition>();

    [ForeignKey("CityId")]
    [InverseProperty("CareRecipients")]
    public virtual City City { get; set; }

    [InverseProperty("CareRecipient")]
    public virtual ICollection<EmergencyContact> EmergencyContacts { get; set; } = new List<EmergencyContact>();

    [ForeignKey("TownshipId")]
    [InverseProperty("CareRecipients")]
    public virtual Township Township { get; set; }

    [InverseProperty("CareRecipient")]
    public virtual ICollection<UserCareRecipient> UserCareRecipients { get; set; } = new List<UserCareRecipient>();
}