// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Team1.VitalBridge.BackStage.Models.EFModels;

[Index("CareRecipientId", "InviteeEmail", Name = "UQ__CareReci__564A052485DB48F3", IsUnique = true)]
public partial class CareRecipientInvitation
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("inviterUserId")]
    public int InviterUserId { get; set; }

    [Column("careRecipientId")]
    public int CareRecipientId { get; set; }

    [Required]
    [Column("inviteeEmail")]
    [StringLength(255)]
    [Unicode(false)]
    public string InviteeEmail { get; set; }

    [Required]
    [Column("status")]
    [StringLength(30)]
    [Unicode(false)]
    public string Status { get; set; }

    [Required]
    [Column("permissionLevel")]
    [StringLength(30)]
    [Unicode(false)]
    public string PermissionLevel { get; set; }

    [Column("confirmCode")]
    [StringLength(50)]
    [Unicode(false)]
    public string ConfirmCode { get; set; }

    [Column("confirmCodeExpiresAt", TypeName = "datetime")]
    public DateTime? ConfirmCodeExpiresAt { get; set; }

    [Column("createdAt", TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [Column("updatedAt", TypeName = "datetime")]
    public DateTime UpdatedAt { get; set; }

    [Column("respondedAt", TypeName = "datetime")]
    public DateTime? RespondedAt { get; set; }

    [ForeignKey("CareRecipientId")]
    [InverseProperty("CareRecipientInvitations")]
    public virtual CareRecipient CareRecipient { get; set; }

    [ForeignKey("InviterUserId")]
    [InverseProperty("CareRecipientInvitations")]
    public virtual User InviterUser { get; set; }
}