// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Team1.VitalBridge.BackStage.Models.EFModels;

[Index("ProductId", "CartId", Name = "UQ__CartItem__B9056150BAEEB7EC", IsUnique = true)]
public partial class CartItem
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("productId")]
    public int ProductId { get; set; }

    [Column("cartId")]
    public int CartId { get; set; }

    [Column("quantity")]
    public int Quantity { get; set; }

    [Column("subtotal", TypeName = "decimal(18, 0)")]
    public decimal Subtotal { get; set; }

    [Column("addAt", TypeName = "datetime")]
    public DateTime AddAt { get; set; }

    [ForeignKey("CartId")]
    [InverseProperty("CartItems")]
    public virtual Cart Cart { get; set; }

    [ForeignKey("ProductId")]
    [InverseProperty("CartItems")]
    public virtual Product Product { get; set; }
}