// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Team1.VitalBridge.BackStage.Models.EFModels;

public partial class Category
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("fatherId")]
    public int? FatherId { get; set; }

    [Required]
    [Column("name")]
    [StringLength(50)]
    public string Name { get; set; }

    [Column("isActive")]
    public bool IsActive { get; set; }

    public int? FileId { get; set; }

    [ForeignKey("FatherId")]
    [InverseProperty("InverseFather")]
    public virtual Category Father { get; set; }

    [ForeignKey("FileId")]
    [InverseProperty("Categories")]
    public virtual FileStream File { get; set; }

    [InverseProperty("Father")]
    public virtual ICollection<Category> InverseFather { get; set; } = new List<Category>();

    [InverseProperty("Category")]
    public virtual ICollection<ProductCategory> ProductCategories { get; set; } = new List<ProductCategory>();
}