// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Team1.VitalBridge.BackStage.Models.EFModels;

[Index("Name", Name = "UQ__Citys__72E12F1B59B172B2", IsUnique = true)]
public partial class City
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("name")]
    [StringLength(10)]
    [Unicode(false)]
    public string Name { get; set; }

    [InverseProperty("City")]
    public virtual ICollection<CareRecipient> CareRecipients { get; set; } = new List<CareRecipient>();

    [InverseProperty("City")]
    public virtual ICollection<EmergencyContact> EmergencyContacts { get; set; } = new List<EmergencyContact>();

    [InverseProperty("City")]
    public virtual ICollection<Institution> Institutions { get; set; } = new List<Institution>();

    [InverseProperty("City")]
    public virtual ICollection<MemberProfile> MemberProfiles { get; set; } = new List<MemberProfile>();

    [InverseProperty("City")]
    public virtual ICollection<OrderShipMethod> OrderShipMethods { get; set; } = new List<OrderShipMethod>();

    [InverseProperty("City")]
    public virtual ICollection<Organization> Organizations { get; set; } = new List<Organization>();

    [InverseProperty("City")]
    public virtual ICollection<Township> Townships { get; set; } = new List<Township>();
}