// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Team1.VitalBridge.BackStage.Models.EFModels;

public partial class ContentTypeCategoryPair
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("contentTypeId")]
    public int ContentTypeId { get; set; }

    [Column("contentCategoryId")]
    public int ContentCategoryId { get; set; }

    [Column("isEnabled")]
    public bool IsEnabled { get; set; }

    [Column("updatedAt", TypeName = "datetime")]
    public DateTime UpdatedAt { get; set; }

    [Column("createdAt", TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [ForeignKey("ContentCategoryId")]
    [InverseProperty("ContentTypeCategoryPairs")]
    public virtual ContentCategory ContentCategory { get; set; }

    [ForeignKey("ContentTypeId")]
    [InverseProperty("ContentTypeCategoryPairs")]
    public virtual ContentType ContentType { get; set; }
}