// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Team1.VitalBridge.BackStage.Models.EFModels;

public partial class ContentCategory
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("name")]
    [StringLength(50)]
    public string Name { get; set; }

    [Column("parentCategoryId")]
    public int? ParentCategoryId { get; set; }

    [Column("isEnabled")]
    public bool IsEnabled { get; set; }

    [Column("displayOrder")]
    public int DisplayOrder { get; set; }

    [Column("updatedAt", TypeName = "datetime")]
    public DateTime UpdatedAt { get; set; }

    [Column("createdAt", TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [InverseProperty("ContentCategory")]
    public virtual ICollection<ContentTypeCategoryPair> ContentTypeCategoryPairs { get; set; } = new List<ContentTypeCategoryPair>();

    [InverseProperty("ContentCategory")]
    public virtual ICollection<Content> Contents { get; set; } = new List<Content>();

    [InverseProperty("ParentCategory")]
    public virtual ICollection<ContentCategory> InverseParentCategory { get; set; } = new List<ContentCategory>();

    [ForeignKey("ParentCategoryId")]
    [InverseProperty("InverseParentCategory")]
    public virtual ContentCategory ParentCategory { get; set; }
}