// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Team1.VitalBridge.BackStage.Models.EFModels;

[Table("CouponRecord")]
[Index("OrderId", Name = "UQ__CouponRe__0809335C2736FA38", IsUnique = true)]
public partial class CouponRecord
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("customerId")]
    public int CustomerId { get; set; }

    [Column("coupounId")]
    public int CoupounId { get; set; }

    [Required]
    [Column("couponCode")]
    [StringLength(50)]
    public string CouponCode { get; set; }

    [Column("discountAmount", TypeName = "decimal(18, 0)")]
    public decimal DiscountAmount { get; set; }

    [Column("orderId")]
    public int OrderId { get; set; }

    [Column("orderAmount", TypeName = "decimal(18, 0)")]
    public decimal OrderAmount { get; set; }

    [Column("ceatedAt", TypeName = "datetime")]
    public DateTime CeatedAt { get; set; }

    [ForeignKey("CoupounId")]
    [InverseProperty("CouponRecords")]
    public virtual Coupon Coupoun { get; set; }

    [ForeignKey("CustomerId")]
    [InverseProperty("CouponRecords")]
    public virtual User Customer { get; set; }

    [ForeignKey("OrderId")]
    [InverseProperty("CouponRecord")]
    public virtual Order Order { get; set; }
}