// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Team1.VitalBridge.BackStage.Models.EFModels;

[Index("CouponCode", Name = "UQ__Coupons__1D19F4DABCDDBE61", IsUnique = true)]
public partial class Coupon
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("name")]
    [StringLength(100)]
    public string Name { get; set; }

    [Required]
    [Column("couponCode")]
    [StringLength(50)]
    public string CouponCode { get; set; }

    [Column("startAt", TypeName = "datetime")]
    public DateTime StartAt { get; set; }

    [Column("endAt", TypeName = "datetime")]
    public DateTime EndAt { get; set; }

    [Column("discount", TypeName = "decimal(18, 0)")]
    public decimal Discount { get; set; }

    [Column("minOrderCost", TypeName = "decimal(18, 0)")]
    public decimal MinOrderCost { get; set; }

    [Column("useageLimit")]
    public int UseageLimit { get; set; }

    [Column("canUseCount")]
    public int CanUseCount { get; set; }

    [Column("isActive")]
    public bool IsActive { get; set; }

    [Column("usedCount")]
    public int? UsedCount { get; set; }

    [Column("createdAt", TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [InverseProperty("Coupoun")]
    public virtual ICollection<CouponRecord> CouponRecords { get; set; } = new List<CouponRecord>();

    [InverseProperty("Coupon")]
    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}