// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Team1.VitalBridge.BackStage.Models.EFModels;

[Index("EmergencyContactId", Name = "UQ__Emergenc__7394A15C1AF5B6BF", IsUnique = true)]
public partial class EmergencyContact
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("emergencyContactId")]
    [StringLength(50)]
    [Unicode(false)]
    public string EmergencyContactId { get; set; }

    [Column("careRecipientId")]
    public int CareRecipientId { get; set; }

    [Column("userId")]
    public int? UserId { get; set; }

    [Required]
    [Column("name")]
    [StringLength(20)]
    [Unicode(false)]
    public string Name { get; set; }

    [Required]
    [Column("gender")]
    [StringLength(5)]
    [Unicode(false)]
    public string Gender { get; set; }

    [Column("email")]
    [StringLength(256)]
    [Unicode(false)]
    public string Email { get; set; }

    [Required]
    [Column("phone")]
    [StringLength(10)]
    [Unicode(false)]
    public string Phone { get; set; }

    [Column("cityId")]
    public int? CityId { get; set; }

    [Column("townshipId")]
    public int? TownshipId { get; set; }

    [Column("address")]
    [StringLength(100)]
    [Unicode(false)]
    public string Address { get; set; }

    [Required]
    [Column("relationship")]
    [StringLength(20)]
    [Unicode(false)]
    public string Relationship { get; set; }

    [Column("priority")]
    public int Priority { get; set; }

    [Column("isMember")]
    public bool IsMember { get; set; }

    [Column("createdAt", TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [Column("updatedAt", TypeName = "datetime")]
    public DateTime UpdatedAt { get; set; }

    [ForeignKey("CareRecipientId")]
    [InverseProperty("EmergencyContacts")]
    public virtual CareRecipient CareRecipient { get; set; }

    [ForeignKey("CityId")]
    [InverseProperty("EmergencyContacts")]
    public virtual City City { get; set; }

    [ForeignKey("TownshipId")]
    [InverseProperty("EmergencyContacts")]
    public virtual Township Township { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("EmergencyContacts")]
    public virtual User User { get; set; }
}