// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Team1.VitalBridge.BackStage.Models.EFModels;

[Table("EventStatus")]
[Index("StatusCode", Name = "UQ__EventSta__AD4366F6FBC90421", IsUnique = true)]
public partial class EventStatus
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("statusCode")]
    [StringLength(50)]
    [Unicode(false)]
    public string StatusCode { get; set; }

    [Required]
    [Column("name")]
    [StringLength(20)]
    [Unicode(false)]
    public string Name { get; set; }

    [InverseProperty("Status")]
    public virtual ICollection<Event> Events { get; set; } = new List<Event>();
}