// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Team1.VitalBridge.BackStage.Models.EFModels;

public partial class EventImage
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("eventId")]
    public int EventId { get; set; }

    [Required]
    [Column("imgName")]
    [StringLength(50)]
    [Unicode(false)]
    public string ImgName { get; set; }

    [Required]
    [Column("imgUrl")]
    [StringLength(255)]
    [Unicode(false)]
    public string ImgUrl { get; set; }

    [Required]
    [Column("mimeType")]
    [StringLength(50)]
    [Unicode(false)]
    public string MimeType { get; set; }

    [Column("isPrimary")]
    public bool IsPrimary { get; set; }

    [Column("createdAt", TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [ForeignKey("EventId")]
    [InverseProperty("EventImages")]
    public virtual Event Event { get; set; }
}