// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Team1.VitalBridge.BackStage.Models.EFModels;

[Index("EventId", Name = "UQ__Events__2DC7BD08AF633B83", IsUnique = true)]
public partial class Event
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("eventId")]
    [StringLength(20)]
    [Unicode(false)]
    public string EventId { get; set; }

    [Required]
    [Column("type")]
    [StringLength(20)]
    [Unicode(false)]
    public string Type { get; set; }

    [Column("organizerId")]
    public int OrganizerId { get; set; }

    [Required]
    [Column("title")]
    [StringLength(30)]
    [Unicode(false)]
    public string Title { get; set; }

    [Column("description")]
    [StringLength(100)]
    [Unicode(false)]
    public string Description { get; set; }

    [Required]
    [Column("details", TypeName = "text")]
    public string Details { get; set; }

    [Column("cityId")]
    public int? CityId { get; set; }

    [Column("townshipId")]
    public int? TownshipId { get; set; }

    [Column("address")]
    [StringLength(100)]
    [Unicode(false)]
    public string Address { get; set; }

    [Column("statusId")]
    public int StatusId { get; set; }

    [Column("startTime", TypeName = "datetime")]
    public DateTime StartTime { get; set; }

    [Column("endTime", TypeName = "datetime")]
    public DateTime EndTime { get; set; }

    [Column("maxParticipants")]
    public int MaxParticipants { get; set; }

    [Column("currentParticipants")]
    public int CurrentParticipants { get; set; }

    [Column("createdAt", TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [Column("updatedAt", TypeName = "datetime")]
    public DateTime UpdatedAt { get; set; }

    [InverseProperty("Event")]
    public virtual ICollection<EventImage> EventImages { get; set; } = new List<EventImage>();

    [InverseProperty("Event")]
    public virtual ICollection<EventParticipant> EventParticipants { get; set; } = new List<EventParticipant>();

    [ForeignKey("StatusId")]
    [InverseProperty("Events")]
    public virtual EventStatus Status { get; set; }

    [ForeignKey("TownshipId")]
    [InverseProperty("Events")]
    public virtual Township Township { get; set; }
}