// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Team1.VitalBridge.BackStage.Models.EFModels;

[PrimaryKey("CustomerId", "ProductId")]
public partial class Favorite
{
    [Key]
    [Column("customerId")]
    public int CustomerId { get; set; }

    [Key]
    [Column("productId")]
    public int ProductId { get; set; }

    [Column("favoritedAt", TypeName = "datetime")]
    public DateTime? FavoritedAt { get; set; }

    [ForeignKey("CustomerId")]
    [InverseProperty("Favorites")]
    public virtual User Customer { get; set; }

    [ForeignKey("ProductId")]
    [InverseProperty("Favorites")]
    public virtual Product Product { get; set; }
}