// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Team1.VitalBridge.BackStage.Models.EFModels;

public partial class FeatureService
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("name")]
    [StringLength(100)]
    public string Name { get; set; }

    public int? FileId { get; set; }

    [ForeignKey("FileId")]
    [InverseProperty("FeatureServices")]
    public virtual FileStream File { get; set; }

    [InverseProperty("FeatureService")]
    public virtual ICollection<OrganizationFeatureService> OrganizationFeatureServices { get; set; } = new List<OrganizationFeatureService>();
}