// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Team1.VitalBridge.BackStage.Models.EFModels;

public partial class HealthCondition
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("name")]
    [StringLength(20)]
    [Unicode(false)]
    public string Name { get; set; }

    [Required]
    [Column("type")]
    [StringLength(20)]
    [Unicode(false)]
    public string Type { get; set; }

    [Column("info")]
    [StringLength(100)]
    [Unicode(false)]
    public string Info { get; set; }

    [Column("isActive")]
    public bool IsActive { get; set; }

    [Column("createdAt", TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [Column("updatedAt", TypeName = "datetime")]
    public DateTime UpdatedAt { get; set; }

    [InverseProperty("HealthConditions")]
    public virtual ICollection<CareRecipientHealthCondition> CareRecipientHealthConditions { get; set; } = new List<CareRecipientHealthCondition>();
}