// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Team1.VitalBridge.BackStage.Models.EFModels;

[Index("Email", Name = "UQ__Institut__AB6E6164D3519AC8", IsUnique = true)]
[Index("UserId", Name = "UQ__Institut__CB9A1CFE9E76597D", IsUnique = true)]
public partial class InstitutionUser
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("institutionId")]
    public int InstitutionId { get; set; }

    [Required]
    [Column("userId")]
    [StringLength(50)]
    [Unicode(false)]
    public string UserId { get; set; }

    [Required]
    [Column("name")]
    [StringLength(20)]
    [Unicode(false)]
    public string Name { get; set; }

    [Required]
    [Column("email")]
    [StringLength(256)]
    [Unicode(false)]
    public string Email { get; set; }

    [Required]
    [Column("password")]
    [StringLength(100)]
    [Unicode(false)]
    public string Password { get; set; }

    [Column("phone")]
    [StringLength(10)]
    [Unicode(false)]
    public string Phone { get; set; }

    [Required]
    [Column("status")]
    [StringLength(20)]
    [Unicode(false)]
    public string Status { get; set; }

    [Column("isMainUser")]
    public bool IsMainUser { get; set; }

    [Column("confirmCode")]
    [StringLength(50)]
    [Unicode(false)]
    public string ConfirmCode { get; set; }

    [Column("confirmCodeExpiresAt", TypeName = "datetime")]
    public DateTime? ConfirmCodeExpiresAt { get; set; }

    [Column("resetPasswordConfirmCode")]
    [StringLength(50)]
    [Unicode(false)]
    public string ResetPasswordConfirmCode { get; set; }

    [Column("resetPasswordConfirmCodeExpiresAt", TypeName = "datetime")]
    public DateTime? ResetPasswordConfirmCodeExpiresAt { get; set; }

    [Column("createdAt", TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [Column("updatedAt", TypeName = "datetime")]
    public DateTime UpdatedAt { get; set; }

    [Column("lastLoginAt", TypeName = "datetime")]
    public DateTime? LastLoginAt { get; set; }

    [ForeignKey("InstitutionId")]
    [InverseProperty("InstitutionUsers")]
    public virtual Institution Institution { get; set; }

    [InverseProperty("User")]
    public virtual ICollection<InstitutionUserRole> InstitutionUserRoles { get; set; } = new List<InstitutionUserRole>();
}