// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Team1.VitalBridge.BackStage.Models.EFModels;

public partial class InstitutionRolePermission
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("roleId")]
    public int RoleId { get; set; }

    [Column("permissionId")]
    public int PermissionId { get; set; }

    [Column("createdAt", TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [Column("updatedAt", TypeName = "datetime")]
    public DateTime UpdatedAt { get; set; }

    [ForeignKey("PermissionId")]
    [InverseProperty("InstitutionRolePermissions")]
    public virtual InstitutionPermission Permission { get; set; }

    [ForeignKey("RoleId")]
    [InverseProperty("InstitutionRolePermissions")]
    public virtual InstitutionRole Role { get; set; }
}