// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Team1.VitalBridge.BackStage.Models.EFModels;

[Index("InstitutionCode", Name = "UQ__Institut__5BDD9EFDB1E185F9", IsUnique = true)]
[Index("Email", Name = "UQ__Institut__AB6E6164E82186CE", IsUnique = true)]
public partial class Institution
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("institutionCode")]
    [StringLength(50)]
    [Unicode(false)]
    public string InstitutionCode { get; set; }

    [Required]
    [Column("name")]
    [StringLength(50)]
    [Unicode(false)]
    public string Name { get; set; }

    [Required]
    [Column("phone")]
    [StringLength(10)]
    [Unicode(false)]
    public string Phone { get; set; }

    [Required]
    [Column("principalName")]
    [StringLength(20)]
    [Unicode(false)]
    public string PrincipalName { get; set; }

    [Required]
    [Column("principalPhone")]
    [StringLength(10)]
    [Unicode(false)]
    public string PrincipalPhone { get; set; }

    [Required]
    [Column("email")]
    [StringLength(256)]
    [Unicode(false)]
    public string Email { get; set; }

    [Required]
    [Column("status")]
    [StringLength(10)]
    [Unicode(false)]
    public string Status { get; set; }

    [Column("cityId")]
    public int CityId { get; set; }

    [Column("townshipId")]
    public int TownshipId { get; set; }

    [Required]
    [Column("address")]
    [StringLength(100)]
    [Unicode(false)]
    public string Address { get; set; }

    [Column("isPhysicalCheck")]
    public bool IsPhysicalCheck { get; set; }

    [Column("isBanned")]
    public bool IsBanned { get; set; }

    [Column("createdAt", TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [Column("updatedAt", TypeName = "datetime")]
    public DateTime UpdatedAt { get; set; }

    [ForeignKey("CityId")]
    [InverseProperty("Institutions")]
    public virtual City City { get; set; }

    [InverseProperty("Institution")]
    public virtual ICollection<InstitutionAuditImage> InstitutionAuditImages { get; set; } = new List<InstitutionAuditImage>();

    [InverseProperty("Institution")]
    public virtual ICollection<InstitutionProfile> InstitutionProfiles { get; set; } = new List<InstitutionProfile>();

    [InverseProperty("Institution")]
    public virtual ICollection<Organization> Organizations { get; set; } = new List<Organization>();

    [ForeignKey("TownshipId")]
    [InverseProperty("Institutions")]
    public virtual Township Township { get; set; }
}