// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Team1.VitalBridge.BackStage.Models.EFModels;

[Index("RoleCode", Name = "UQ__Institut__44FD4F90456F6E2C", IsUnique = true)]
public partial class InstitutionRole
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("roleCode")]
    [StringLength(30)]
    [Unicode(false)]
    public string RoleCode { get; set; }

    [Required]
    [Column("name")]
    [StringLength(20)]
    [Unicode(false)]
    public string Name { get; set; }

    [Column("info")]
    [StringLength(100)]
    [Unicode(false)]
    public string Info { get; set; }

    [Column("isActive")]
    public bool IsActive { get; set; }

    [Column("createdAt", TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [Column("updatedAt", TypeName = "datetime")]
    public DateTime UpdatedAt { get; set; }

    [InverseProperty("Role")]
    public virtual ICollection<InstitutionRolePermission> InstitutionRolePermissions { get; set; } = new List<InstitutionRolePermission>();

    [InverseProperty("Role")]
    public virtual ICollection<InstitutionUserRole> InstitutionUserRoles { get; set; } = new List<InstitutionUserRole>();
}