// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Team1.VitalBridge.BackStage.Models.EFModels;

public partial class Log
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("userId")]
    public int UserId { get; set; }

    [Column("info")]
    [StringLength(100)]
    [Unicode(false)]
    public string Info { get; set; }

    [Required]
    [Column("type")]
    [StringLength(30)]
    [Unicode(false)]
    public string Type { get; set; }

    [Column("createdAt", TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [Column("ipAddress")]
    [StringLength(50)]
    [Unicode(false)]
    public string IpAddress { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("Logs")]
    public virtual User User { get; set; }
}