// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Team1.VitalBridge.BackStage.Models.EFModels;

[Index("UserId", Name = "UQ__MemberPr__CB9A1CFECA0DAF95", IsUnique = true)]
public partial class MemberProfile
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("userId")]
    public int UserId { get; set; }

    [Column("cityId")]
    public int? CityId { get; set; }

    [Column("townshipId")]
    public int? TownshipId { get; set; }

    [Column("address")]
    [StringLength(100)]
    [Unicode(false)]
    public string Address { get; set; }

    [Column("createdAt", TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [Column("updatedAt", TypeName = "datetime")]
    public DateTime UpdatedAt { get; set; }

    [ForeignKey("CityId")]
    [InverseProperty("MemberProfiles")]
    public virtual City City { get; set; }

    [ForeignKey("TownshipId")]
    [InverseProperty("MemberProfiles")]
    public virtual Township Township { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("MemberProfile")]
    public virtual User User { get; set; }
}