// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Team1.VitalBridge.BackStage.Models.EFModels;

public partial class Notify
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("title")]
    [StringLength(50)]
    public string Title { get; set; }

    [Column("text")]
    [StringLength(500)]
    public string Text { get; set; }

    [Column("notifysUrl")]
    [StringLength(500)]
    public string NotifysUrl { get; set; }

    [Column("categoriesId")]
    public int CategoriesId { get; set; }

    [Column("sendDate", TypeName = "datetime")]
    public DateTime SendDate { get; set; }

    [Column("validityDate", TypeName = "datetime")]
    public DateTime? ValidityDate { get; set; }

    [ForeignKey("CategoriesId")]
    [InverseProperty("Notifies")]
    public virtual NotifysCategory Categories { get; set; }

    [InverseProperty("Notify")]
    public virtual ICollection<NotifyUser> NotifyUsers { get; set; } = new List<NotifyUser>();
}