// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Team1.VitalBridge.BackStage.Models.EFModels;

[Table("NotifysCategory")]
[Index("Name", Name = "UQ__NotifysC__72E12F1B518BC953", IsUnique = true)]
public partial class NotifysCategory
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("name")]
    [StringLength(20)]
    public string Name { get; set; }

    [Column("enable")]
    public bool Enable { get; set; }

    [InverseProperty("Categories")]
    public virtual ICollection<Notify> Notifies { get; set; } = new List<Notify>();
}