// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Team1.VitalBridge.BackStage.Models.EFModels;

[Index("OrderNumber", Name = "UQ__Orders__6296129FA57CCEE4", IsUnique = true)]
public partial class Order
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("orderNumber")]
    [StringLength(100)]
    public string OrderNumber { get; set; }

    [Column("customerId")]
    public int CustomerId { get; set; }

    [Column("shippingFee", TypeName = "decimal(18, 0)")]
    public decimal ShippingFee { get; set; }

    [Column("couponId")]
    public int? CouponId { get; set; }

    [Column("couponDiscount", TypeName = "decimal(18, 0)")]
    public decimal? CouponDiscount { get; set; }

    [Column("subtotalAmount", TypeName = "decimal(18, 0)")]
    public decimal SubtotalAmount { get; set; }

    [Column("totalAmount", TypeName = "decimal(18, 0)")]
    public decimal TotalAmount { get; set; }

    [Column("note")]
    [StringLength(1000)]
    public string Note { get; set; }

    [Column("createdAt", TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [Column("updatedAt", TypeName = "datetime")]
    public DateTime UpdatedAt { get; set; }

    [ForeignKey("CouponId")]
    [InverseProperty("Orders")]
    public virtual Coupon Coupon { get; set; }

    [InverseProperty("Order")]
    public virtual CouponRecord CouponRecord { get; set; }

    [ForeignKey("CustomerId")]
    [InverseProperty("Orders")]
    public virtual User Customer { get; set; }

    [InverseProperty("Order")]
    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();

    [InverseProperty("Order")]
    public virtual OrderRecipent OrderRecipent { get; set; }

    [InverseProperty("Order")]
    public virtual OrderShipMethod OrderShipMethod { get; set; }

    [InverseProperty("Order")]
    public virtual ICollection<OrderStatus> OrderStatuses { get; set; } = new List<OrderStatus>();

    [InverseProperty("Order")]
    public virtual Payment Payment { get; set; }
}