// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Team1.VitalBridge.BackStage.Models.EFModels;

[Index("OrderId", Name = "UQ__OrderRec__0809335C077FCE0B", IsUnique = true)]
public partial class OrderRecipent
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("orderId")]
    public int OrderId { get; set; }

    [Required]
    [Column("recipentName")]
    [StringLength(100)]
    public string RecipentName { get; set; }

    [Required]
    [Column("recipentPhone")]
    [StringLength(20)]
    public string RecipentPhone { get; set; }

    [ForeignKey("OrderId")]
    [InverseProperty("OrderRecipent")]
    public virtual Order Order { get; set; }
}