// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Team1.VitalBridge.BackStage.Models.EFModels;

[Table("OrderStatus")]
public partial class OrderStatus
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("orderId")]
    public int OrderId { get; set; }

    [Column("orderStatusItemId")]
    public int OrderStatusItemId { get; set; }

    [Column("createdAt", TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [ForeignKey("OrderId")]
    [InverseProperty("OrderStatuses")]
    public virtual Order Order { get; set; }

    [ForeignKey("OrderStatusItemId")]
    [InverseProperty("OrderStatuses")]
    public virtual OrderStatusItem OrderStatusItem { get; set; }
}