// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Team1.VitalBridge.BackStage.Models.EFModels;

public partial class OrganizationRoom
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("organizationId")]
    public int? OrganizationId { get; set; }

    [Column("roomTypeId")]
    public int? RoomTypeId { get; set; }

    [Column("monthlyPrice")]
    public int? MonthlyPrice { get; set; }

    [Column("roomQuantity")]
    public int? RoomQuantity { get; set; }

    [Column("hasDeposit")]
    public bool? HasDeposit { get; set; }

    [Column("depositAmount")]
    public int? DepositAmount { get; set; }

    [Column("depositMonths", TypeName = "decimal(3, 1)")]
    public decimal? DepositMonths { get; set; }

    [ForeignKey("OrganizationId")]
    [InverseProperty("OrganizationRooms")]
    public virtual Organization Organization { get; set; }

    [ForeignKey("RoomTypeId")]
    [InverseProperty("OrganizationRooms")]
    public virtual RoomType RoomType { get; set; }
}