// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Team1.VitalBridge.BackStage.Models.EFModels;

public partial class OrganizationSubsidyInfo
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("organizationId")]
    public int OrganizationId { get; set; }

    [Column("subsidyInfoId")]
    public int SubsidyInfoId { get; set; }

    [ForeignKey("OrganizationId")]
    [InverseProperty("OrganizationSubsidyInfos")]
    public virtual Organization Organization { get; set; }

    [ForeignKey("SubsidyInfoId")]
    [InverseProperty("OrganizationSubsidyInfos")]
    public virtual SubsidyInfo SubsidyInfo { get; set; }
}