// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Team1.VitalBridge.BackStage.Models.EFModels;

public partial class OrganizationServiceTarget
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("organizationId")]
    public int OrganizationId { get; set; }

    [Column("serviceTargetId")]
    public int ServiceTargetId { get; set; }

    [ForeignKey("OrganizationId")]
    [InverseProperty("OrganizationServiceTargets")]
    public virtual Organization Organization { get; set; }

    [ForeignKey("ServiceTargetId")]
    [InverseProperty("OrganizationServiceTargets")]
    public virtual ServiceTarget ServiceTarget { get; set; }
}