// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Team1.VitalBridge.BackStage.Models.EFModels;

public partial class OrganizationType
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("name")]
    [StringLength(100)]
    [Display(Name = "機構類型名稱")]
    public string Name { get; set; }

    public bool IsActive { get; set; }

    [InverseProperty("Type")]
    public virtual ICollection<Organization> Organizations { get; set; } = new List<Organization>();
}