// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Team1.VitalBridge.BackStage.Models.EFModels;

[Index("Name", Name = "UQ__PaymentM__72E12F1BE738B99E", IsUnique = true)]
public partial class PaymentMethod
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("name")]
    [StringLength(50)]
    public string Name { get; set; }

    [Column("isActive")]
    public bool IsActive { get; set; }

    [InverseProperty("PayMethod")]
    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();
}