// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Team1.VitalBridge.BackStage.Models.EFModels;

[Table("Payment")]
[Index("OrderId", Name = "UQ__Payment__0809335C56FE3ED5", IsUnique = true)]
public partial class Payment
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("orderId")]
    public int OrderId { get; set; }

    [Column("payMethodId")]
    public int PayMethodId { get; set; }

    [Required]
    [Column("status")]
    [StringLength(50)]
    public string Status { get; set; }

    [Column("paidAt", TypeName = "datetime")]
    public DateTime? PaidAt { get; set; }

    [Column("amount", TypeName = "decimal(18, 0)")]
    public decimal Amount { get; set; }

    [Column("transactionId")]
    [StringLength(100)]
    public string TransactionId { get; set; }

    [Column("creatAt", TypeName = "datetime")]
    public DateTime CreatAt { get; set; }

    [Column("updatedAt", TypeName = "datetime")]
    public DateTime UpdatedAt { get; set; }

    [ForeignKey("OrderId")]
    [InverseProperty("Payment")]
    public virtual Order Order { get; set; }

    [ForeignKey("PayMethodId")]
    [InverseProperty("Payments")]
    public virtual PaymentMethod PayMethod { get; set; }
}