// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Team1.VitalBridge.BackStage.Models.EFModels;

[Index("ProductId", "ShipId", Name = "UQ__ProductS__61D8A2D757C01D81", IsUnique = true)]
public partial class ProductShip
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("productId")]
    public int ProductId { get; set; }

    [Column("shipId")]
    public int ShipId { get; set; }

    [Column("isActive")]
    public bool IsActive { get; set; }

    [ForeignKey("ProductId")]
    [InverseProperty("ProductShips")]
    public virtual Product Product { get; set; }

    [ForeignKey("ShipId")]
    [InverseProperty("ProductShips")]
    public virtual Ship Ship { get; set; }
}