// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Team1.VitalBridge.BackStage.Models.EFModels;

[Table("ProductNote")]
public partial class ProductNote
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("shoppNote")]
    public string ShoppNote { get; set; }

    [Column("deliveryAndPayMethod")]
    public string DeliveryAndPayMethod { get; set; }

    [Column("createdAt", TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }
}