// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Team1.VitalBridge.BackStage.Models.EFModels;

[Index("RoleCode", Name = "UQ__Roles__44FD4F9001B9E2A6", IsUnique = true)]
public partial class Role
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("roleCode")]
    [StringLength(50)]
    [Unicode(false)]
    public string RoleCode { get; set; }

    [Required]
    [Column("name")]
    [StringLength(20)]
    [Unicode(false)]
    public string Name { get; set; }

    [Column("info")]
    [StringLength(100)]
    [Unicode(false)]
    public string Info { get; set; }

    [Column("isActive")]
    public bool IsActive { get; set; }

    [Required]
    [Column("roleType")]
    [StringLength(30)]
    [Unicode(false)]
    public string RoleType { get; set; }

    [Column("isSystemDefault")]
    public bool IsSystemDefault { get; set; }

    [Column("createdAt", TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [Column("updatedAt", TypeName = "datetime")]
    public DateTime UpdatedAt { get; set; }

    [InverseProperty("Role")]
    public virtual ICollection<RolePermission> RolePermissions { get; set; } = new List<RolePermission>();

    [InverseProperty("Role")]
    public virtual ICollection<UserRole> UserRoles { get; set; } = new List<UserRole>();
}