// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Team1.VitalBridge.BackStage.Models.EFModels;

public partial class ServiceTarget
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Display(Name = "服務對象")]
    [Required]
    [Column("name")]
    [StringLength(100)]
    public string Name { get; set; }

    public bool IsActive { get; set; }

    [InverseProperty("ServiceTarget")]
    public virtual ICollection<OrganizationServiceTarget> OrganizationServiceTargets { get; set; } = new List<OrganizationServiceTarget>();
}