// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Team1.VitalBridge.BackStage.Models.EFModels;

[Index("ShipMethodName", Name = "UQ__Ships__DC90D6A18437BC13", IsUnique = true)]
public partial class Ship
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("shipMethodName")]
    [StringLength(50)]
    public string ShipMethodName { get; set; }

    [Column("shipCost", TypeName = "decimal(10, 2)")]
    public decimal ShipCost { get; set; }

    [Column("isActive")]
    public bool? IsActive { get; set; }

    [InverseProperty("Ship")]
    public virtual ICollection<OrderShipMethod> OrderShipMethods { get; set; } = new List<OrderShipMethod>();

    [InverseProperty("Ship")]
    public virtual ICollection<ProductShip> ProductShips { get; set; } = new List<ProductShip>();
}