// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Team1.VitalBridge.BackStage.Models.EFModels;

public partial class ShopHomePageBanner
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("position")]
    public int Position { get; set; }

    [Column("landingPageUrl")]
    public string LandingPageUrl { get; set; }

    [Column("isActive")]
    public bool IsActive { get; set; }

    [Column("createAt", TypeName = "datetime")]
    public DateTime CreateAt { get; set; }

    [Column("updated", TypeName = "datetime")]
    public DateTime Updated { get; set; }

    public int? FileId { get; set; }

    [ForeignKey("FileId")]
    [InverseProperty("ShopHomePageBanners")]
    public virtual FileStream File { get; set; }
}