// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Team1.VitalBridge.BackStage.Models.EFModels;

public partial class SubsidyInfo
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("description")]
    [StringLength(100)]
    [Display(Name = "補助描述")]
    public string Description { get; set; }

    [InverseProperty("SubsidyInfo")]
    public virtual ICollection<OrganizationSubsidyInfo> OrganizationSubsidyInfos { get; set; } = new List<OrganizationSubsidyInfo>();
}