// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Team1.VitalBridge.Frontend.Models.EFModels;

public partial class AdminProfile
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public bool IsSuperAdmin { get; set; }

    public int? CreatedByUserId { get; set; }

    public string Note { get; set; }

    public DateTime? LastAdminActionAt { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual User User { get; set; }
}