// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Team1.VitalBridge.Frontend.Models.EFModels;

public partial class AppDbContext : DbContext
{
    public AppDbContext()
    {
    }

    public AppDbContext(DbContextOptions<AppDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AdminProfile> AdminProfiles { get; set; }

    public virtual DbSet<CareRecipient> CareRecipients { get; set; }

    public virtual DbSet<CareRecipientHealthCondition> CareRecipientHealthConditions { get; set; }

    public virtual DbSet<CareRecipientInvitation> CareRecipientInvitations { get; set; }

    public virtual DbSet<CareRecipientsImage> CareRecipientsImages { get; set; }

    public virtual DbSet<Cart> Carts { get; set; }

    public virtual DbSet<CartItem> CartItems { get; set; }

    public virtual DbSet<Category> Categories { get; set; }

    public virtual DbSet<City> Citys { get; set; }

    public virtual DbSet<Comment> Comments { get; set; }

    public virtual DbSet<Content> Contents { get; set; }

    public virtual DbSet<ContentCategory> ContentCategories { get; set; }

    public virtual DbSet<Coupon> Coupons { get; set; }

    public virtual DbSet<CouponRecord> CouponRecords { get; set; }

    public virtual DbSet<EmergencyContact> EmergencyContacts { get; set; }

    public virtual DbSet<Event> Events { get; set; }

    public virtual DbSet<EventImage> EventImages { get; set; }

    public virtual DbSet<EventParticipant> EventParticipants { get; set; }

    public virtual DbSet<EventStatus> EventStatuses { get; set; }

    public virtual DbSet<ExternalLogin> ExternalLogins { get; set; }

    public virtual DbSet<Favorite> Favorites { get; set; }

    public virtual DbSet<FeatureService> FeatureServices { get; set; }

    public virtual DbSet<FileStream> FileStreams { get; set; }

    public virtual DbSet<HealthCondition> HealthConditions { get; set; }

    public virtual DbSet<Institution> Institutions { get; set; }

    public virtual DbSet<InstitutionAuditImage> InstitutionAuditImages { get; set; }

    public virtual DbSet<InstitutionProfile> InstitutionProfiles { get; set; }

    public virtual DbSet<Log> Logs { get; set; }

    public virtual DbSet<Media> Medias { get; set; }

    public virtual DbSet<MediaType> MediaTypes { get; set; }

    public virtual DbSet<MemberProfile> MemberProfiles { get; set; }

    public virtual DbSet<Notify> Notifys { get; set; }

    public virtual DbSet<NotifyUser> NotifyUsers { get; set; }

    public virtual DbSet<NotifysCategory> NotifysCategories { get; set; }

    public virtual DbSet<Order> Orders { get; set; }

    public virtual DbSet<OrderItem> OrderItems { get; set; }

    public virtual DbSet<OrderRecipent> OrderRecipents { get; set; }

    public virtual DbSet<OrderShipMethod> OrderShipMethods { get; set; }

    public virtual DbSet<OrderStatus> OrderStatuses { get; set; }

    public virtual DbSet<OrderStatusItem> OrderStatusItems { get; set; }

    public virtual DbSet<Organization> Organizations { get; set; }

    public virtual DbSet<OrganizationCertificationRequest> OrganizationCertificationRequests { get; set; }

    public virtual DbSet<OrganizationFeatureService> OrganizationFeatureServices { get; set; }

    public virtual DbSet<OrganizationRoom> OrganizationRooms { get; set; }

    public virtual DbSet<OrganizationServiceTarget> OrganizationServiceTargets { get; set; }

    public virtual DbSet<OrganizationSubsidyInfo> OrganizationSubsidyInfos { get; set; }

    public virtual DbSet<OrganizationType> OrganizationTypes { get; set; }

    public virtual DbSet<Payment> Payments { get; set; }

    public virtual DbSet<PaymentMethod> PaymentMethods { get; set; }

    public virtual DbSet<PaymentStatus> PaymentStatuses { get; set; }

    public virtual DbSet<Permission> Permissions { get; set; }

    public virtual DbSet<Plate> Plates { get; set; }

    public virtual DbSet<PlateImage> PlateImages { get; set; }

    public virtual DbSet<Product> Products { get; set; }

    public virtual DbSet<ProductCategory> ProductCategories { get; set; }

    public virtual DbSet<ProductImage> ProductImages { get; set; }

    public virtual DbSet<ProductNote> ProductNotes { get; set; }

    public virtual DbSet<ProductShip> ProductShips { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<RolePermission> RolePermissions { get; set; }

    public virtual DbSet<RoomType> RoomTypes { get; set; }

    public virtual DbSet<ServiceTarget> ServiceTargets { get; set; }

    public virtual DbSet<Ship> Ships { get; set; }

    public virtual DbSet<ShippingRule> ShippingRules { get; set; }

    public virtual DbSet<ShopHomePageBanner> ShopHomePageBanners { get; set; }

    public virtual DbSet<SubsidyInfo> SubsidyInfos { get; set; }

    public virtual DbSet<Township> Townships { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<UserCareRecipient> UserCareRecipients { get; set; }

    public virtual DbSet<UserRole> UserRoles { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=40.76.107.125;Initial Catalog=VitalBridgeDB;Persist Security Info=True;User ID=prjTeam1;Password=VitalBridge123");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AdminProfile>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__AdminPro__3213E83F07B674F6");

            entity.HasIndex(e => e.UserId, "UQ__AdminPro__CB9A1CFE2CE53106").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CreatedAt)
                .HasColumnType("datetime")
                .HasColumnName("createdAt");
            entity.Property(e => e.CreatedByUserId).HasColumnName("createdByUserId");
            entity.Property(e => e.IsSuperAdmin).HasColumnName("isSuperAdmin");
            entity.Property(e => e.LastAdminActionAt)
                .HasColumnType("datetime")
                .HasColumnName("lastAdminActionAt");
            entity.Property(e => e.Note)
                .HasMaxLength(500)
                .IsUnicode(false)
                .HasColumnName("note");
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("datetime")
                .HasColumnName("updatedAt");
            entity.Property(e => e.UserId).HasColumnName("userId");

            entity.HasOne(d => d.User).WithOne(p => p.AdminProfile)
                .HasForeignKey<AdminProfile>(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__AdminProf__userI__7720AD13");
        });

        modelBuilder.Entity<CareRecipient>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__CareReci__3213E83FA529701A");

            entity.HasIndex(e => e.CareRecipientId, "UQ__CareReci__ED1D489726D8C91B").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Address)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("address");
            entity.Property(e => e.BirthDate).HasColumnName("birthDate");
            entity.Property(e => e.CareLevel).HasColumnName("careLevel");
            entity.Property(e => e.CareRecipientId)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("careRecipientId");
            entity.Property(e => e.CityId).HasColumnName("cityId");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("createdAt");
            entity.Property(e => e.Gender)
                .IsRequired()
                .HasMaxLength(5)
                .IsUnicode(false)
                .HasColumnName("gender");
            entity.Property(e => e.Height).HasColumnName("height");
            entity.Property(e => e.IsActive).HasColumnName("isActive");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("name");
            entity.Property(e => e.Phone)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("phone");
            entity.Property(e => e.TownshipId).HasColumnName("townshipId");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("updatedAt");
            entity.Property(e => e.Weight).HasColumnName("weight");

            entity.HasOne(d => d.City).WithMany(p => p.CareRecipients)
                .HasForeignKey(d => d.CityId)
                .HasConstraintName("FK__CareRecip__cityI__2F9A1060");

            entity.HasOne(d => d.Township).WithMany(p => p.CareRecipients)
                .HasForeignKey(d => d.TownshipId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FK__CareRecip__towns__308E3499");
        });

        modelBuilder.Entity<CareRecipientHealthCondition>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__CareReci__3213E83F5AA55A48");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CareRecipientId).HasColumnName("careRecipientId");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("createdAt");
            entity.Property(e => e.HealthConditionsId).HasColumnName("healthConditionsId");

            entity.HasOne(d => d.CareRecipient).WithMany(p => p.CareRecipientHealthConditions)
                .HasForeignKey(d => d.CareRecipientId)
                .HasConstraintName("FK__CareRecip__careR__477199F1");

            entity.HasOne(d => d.HealthConditions).WithMany(p => p.CareRecipientHealthConditions)
                .HasForeignKey(d => d.HealthConditionsId)
                .HasConstraintName("FK__CareRecip__healt__4865BE2A");
        });

        modelBuilder.Entity<CareRecipientInvitation>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__CareReci__3213E83FB23FA1D4");

            entity.HasIndex(e => new { e.CareRecipientId, e.InviteeEmail }, "UQ__CareReci__564A05248AD9ED47").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CareRecipientId).HasColumnName("careRecipientId");
            entity.Property(e => e.ConfirmCode)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("confirmCode");
            entity.Property(e => e.ConfirmCodeExpiresAt)
                .HasColumnType("datetime")
                .HasColumnName("confirmCodeExpiresAt");
            entity.Property(e => e.CreatedAt)
                .HasColumnType("datetime")
                .HasColumnName("createdAt");
            entity.Property(e => e.InviteeEmail)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("inviteeEmail");
            entity.Property(e => e.InviterUserId).HasColumnName("inviterUserId");
            entity.Property(e => e.PermissionLevel)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasColumnName("permissionLevel");
            entity.Property(e => e.RespondedAt)
                .HasColumnType("datetime")
                .HasColumnName("respondedAt");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasColumnName("status");
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("datetime")
                .HasColumnName("updatedAt");

            entity.HasOne(d => d.CareRecipient).WithMany(p => p.CareRecipientInvitations)
                .HasForeignKey(d => d.CareRecipientId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__CareRecip__careR__038683F8");

            entity.HasOne(d => d.InviterUser).WithMany(p => p.CareRecipientInvitations)
                .HasForeignKey(d => d.InviterUserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__CareRecip__invit__047AA831");
        });

        modelBuilder.Entity<CareRecipientsImage>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__CareReci__3213E83F6EF7D2D7");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CareRecipientId).HasColumnName("careRecipientId");
            entity.Property(e => e.CreatedAt)
                .HasColumnType("datetime")
                .HasColumnName("createdAt");
            entity.Property(e => e.ImgName)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("imgName");
            entity.Property(e => e.MimeType)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("mimeType");
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("datetime")
                .HasColumnName("updatedAt");

            entity.HasOne(d => d.CareRecipient).WithMany(p => p.CareRecipientsImages)
                .HasForeignKey(d => d.CareRecipientId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__CareRecip__careR__7FB5F314");

            entity.HasOne(d => d.File).WithMany(p => p.CareRecipientsImages)
                .HasForeignKey(d => d.FileId)
                .HasConstraintName("FK__CareRecip__FileI__7EC1CEDB");
        });

        modelBuilder.Entity<Cart>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Carts__3213E83F2D6BDB90");

            entity.HasIndex(e => e.CustomerId, "UQ__Carts__B611CB7C8AB87D0B").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CreateAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("createAt");
            entity.Property(e => e.CustomerId).HasColumnName("customerId");

            entity.HasOne(d => d.Customer).WithOne(p => p.Cart)
                .HasForeignKey<Cart>(d => d.CustomerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Carts__customerI__2EDAF651");
        });

        modelBuilder.Entity<CartItem>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__CartItem__3213E83F9C7FCCF4");

            entity.HasIndex(e => new { e.ProductId, e.CartId }, "UQ__CartItem__B90561504AF4BC7C").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.AddAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("addAt");
            entity.Property(e => e.CartId).HasColumnName("cartId");
            entity.Property(e => e.ProductId).HasColumnName("productId");
            entity.Property(e => e.Quantity).HasColumnName("quantity");
            entity.Property(e => e.Subtotal)
                .HasColumnType("decimal(18, 0)")
                .HasColumnName("subtotal");

            entity.HasOne(d => d.Cart).WithMany(p => p.CartItems)
                .HasForeignKey(d => d.CartId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__CartItems__cartI__3A4CA8FD");

            entity.HasOne(d => d.Product).WithMany(p => p.CartItems)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__CartItems__produ__395884C4");
        });

        modelBuilder.Entity<Category>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Categori__3213E83F3C576E93");

            entity.ToTable(tb => tb.HasTrigger("TR_Categories_ParentChildActiveSync"));

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.FatherId).HasColumnName("fatherId");
            entity.Property(e => e.IsActive).HasColumnName("isActive");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("name");

            entity.HasOne(d => d.Father).WithMany(p => p.InverseFather)
                .HasForeignKey(d => d.FatherId)
                .HasConstraintName("FK__Categorie__fathe__3E1D39E1");

            entity.HasOne(d => d.File).WithMany(p => p.Categories)
                .HasForeignKey(d => d.FileId)
                .HasConstraintName("FK__Categorie__FileI__40058253");
        });

        modelBuilder.Entity<City>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Citys__3213E83F5FC001E5");

            entity.HasIndex(e => e.Name, "UQ__Citys__72E12F1B0A120127").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("name");
        });

        modelBuilder.Entity<Comment>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Comments__3213E83F7B41A909");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Content)
                .IsRequired()
                .HasColumnName("content");
            entity.Property(e => e.ContentId).HasColumnName("contentId");
            entity.Property(e => e.CreatedAt)
                .HasColumnType("datetime")
                .HasColumnName("createdAt");
            entity.Property(e => e.IsEnabled).HasColumnName("isEnabled");
            entity.Property(e => e.MemberId).HasColumnName("memberId");
            entity.Property(e => e.ParentCommentId).HasColumnName("parentCommentId");
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("datetime")
                .HasColumnName("updatedAt");

            entity.HasOne(d => d.ContentNavigation).WithMany(p => p.Comments)
                .HasForeignKey(d => d.ContentId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Comments__conten__7C4F7684");

            entity.HasOne(d => d.ParentComment).WithMany(p => p.InverseParentComment)
                .HasForeignKey(d => d.ParentCommentId)
                .HasConstraintName("FK__Comments__parent__7B5B524B");
        });

        modelBuilder.Entity<Content>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Contents__3213E83F7BEA058B");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Content1)
                .IsRequired()
                .HasColumnName("content");
            entity.Property(e => e.ContentCategoryId).HasColumnName("contentCategoryId");
            entity.Property(e => e.CoverPic)
                .HasColumnType("image")
                .HasColumnName("coverPic");
            entity.Property(e => e.CreatedAt)
                .HasColumnType("datetime")
                .HasColumnName("createdAt");
            entity.Property(e => e.MemberId).HasColumnName("memberId");
            entity.Property(e => e.Status).HasColumnName("status");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("title");
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("datetime")
                .HasColumnName("updatedAt");
            entity.Property(e => e.ViewCount).HasColumnName("viewCount");

            entity.HasOne(d => d.ContentCategory).WithMany(p => p.Contents)
                .HasForeignKey(d => d.ContentCategoryId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Contents__conten__73BA3083");
        });

        modelBuilder.Entity<ContentCategory>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__ContentC__3213E83F760997F7");

            entity.HasIndex(e => new { e.Name, e.ParentCategoryId }, "UQ__ContentC__9E071C07B7BC59A8").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CreatedAt)
                .HasColumnType("datetime")
                .HasColumnName("createdAt");
            entity.Property(e => e.DisplayOrder).HasColumnName("displayOrder");
            entity.Property(e => e.IsEnabled).HasColumnName("isEnabled");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("name");
            entity.Property(e => e.ParentCategoryId).HasColumnName("parentCategoryId");
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("datetime")
                .HasColumnName("updatedAt");

            entity.HasOne(d => d.ParentCategory).WithMany(p => p.InverseParentCategory)
                .HasForeignKey(d => d.ParentCategoryId)
                .HasConstraintName("FK__ContentCa__paren__70DDC3D8");
        });

        modelBuilder.Entity<Coupon>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Coupons__3213E83FE3935694");

            entity.HasIndex(e => e.CouponCode, "UQ__Coupons__1D19F4DA9E629E09").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CanUseCount)
                .HasDefaultValue(1)
                .HasColumnName("canUseCount");
            entity.Property(e => e.CouponCode)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("couponCode");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("createdAt");
            entity.Property(e => e.Discount)
                .HasColumnType("decimal(18, 0)")
                .HasColumnName("discount");
            entity.Property(e => e.EndAt)
                .HasColumnType("datetime")
                .HasColumnName("endAt");
            entity.Property(e => e.IsActive).HasColumnName("isActive");
            entity.Property(e => e.MinOrderCost)
                .HasColumnType("decimal(18, 0)")
                .HasColumnName("minOrderCost");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("name");
            entity.Property(e => e.StartAt)
                .HasColumnType("datetime")
                .HasColumnName("startAt");
            entity.Property(e => e.UseageLimit).HasColumnName("useageLimit");
            entity.Property(e => e.UsedCount)
                .HasDefaultValue(0)
                .HasColumnName("usedCount");
        });

        modelBuilder.Entity<CouponRecord>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__CouponRe__3213E83F4BB9E71F");

            entity.ToTable("CouponRecord");

            entity.HasIndex(e => e.OrderId, "UQ__CouponRe__0809335CDB97C394").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CeatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("ceatedAt");
            entity.Property(e => e.CouponCode)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("couponCode");
            entity.Property(e => e.CoupounId).HasColumnName("coupounId");
            entity.Property(e => e.CustomerId).HasColumnName("customerId");
            entity.Property(e => e.DiscountAmount)
                .HasColumnType("decimal(18, 0)")
                .HasColumnName("discountAmount");
            entity.Property(e => e.OrderAmount)
                .HasColumnType("decimal(18, 0)")
                .HasColumnName("orderAmount");
            entity.Property(e => e.OrderId).HasColumnName("orderId");

            entity.HasOne(d => d.Coupoun).WithMany(p => p.CouponRecords)
                .HasForeignKey(d => d.CoupounId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__CouponRec__coupo__7EF6D905");

            entity.HasOne(d => d.Customer).WithMany(p => p.CouponRecords)
                .HasForeignKey(d => d.CustomerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__CouponRec__custo__7E02B4CC");

            entity.HasOne(d => d.Order).WithOne(p => p.CouponRecord)
                .HasForeignKey<CouponRecord>(d => d.OrderId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__CouponRec__order__7FEAFD3E");
        });

        modelBuilder.Entity<EmergencyContact>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Emergenc__3213E83F61C997FD");

            entity.HasIndex(e => e.EmergencyContactId, "UQ__Emergenc__7394A15C5AE63D43").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Address)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("address");
            entity.Property(e => e.CareRecipientId).HasColumnName("careRecipientId");
            entity.Property(e => e.CityId).HasColumnName("cityId");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("createdAt");
            entity.Property(e => e.Email)
                .HasMaxLength(256)
                .IsUnicode(false)
                .HasColumnName("email");
            entity.Property(e => e.EmergencyContactId)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("emergencyContactId");
            entity.Property(e => e.Gender)
                .IsRequired()
                .HasMaxLength(5)
                .IsUnicode(false)
                .HasColumnName("gender");
            entity.Property(e => e.IsMember).HasColumnName("isMember");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("name");
            entity.Property(e => e.Phone)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("phone");
            entity.Property(e => e.Priority).HasColumnName("priority");
            entity.Property(e => e.Relationship)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("relationship");
            entity.Property(e => e.TownshipId).HasColumnName("townshipId");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("updatedAt");
            entity.Property(e => e.UserId).HasColumnName("userId");

            entity.HasOne(d => d.CareRecipient).WithMany(p => p.EmergencyContacts)
                .HasForeignKey(d => d.CareRecipientId)
                .HasConstraintName("FK__Emergency__updat__4E1E9780");

            entity.HasOne(d => d.City).WithMany(p => p.EmergencyContacts)
                .HasForeignKey(d => d.CityId)
                .HasConstraintName("FK__Emergency__cityI__5006DFF2");

            entity.HasOne(d => d.Township).WithMany(p => p.EmergencyContacts)
                .HasForeignKey(d => d.TownshipId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FK__Emergency__towns__50FB042B");

            entity.HasOne(d => d.User).WithMany(p => p.EmergencyContacts)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FK__Emergency__userI__4F12BBB9");
        });

        modelBuilder.Entity<Event>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Events__3213E83F2538B538");

            entity.HasIndex(e => e.EventId, "UQ__Events__2DC7BD08AF633B83").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Address)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("address");
            entity.Property(e => e.CityId).HasColumnName("cityId");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("createdAt");
            entity.Property(e => e.CurrentParticipants).HasColumnName("currentParticipants");
            entity.Property(e => e.Description)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("description");
            entity.Property(e => e.Details)
                .IsRequired()
                .HasColumnType("text")
                .HasColumnName("details");
            entity.Property(e => e.EndTime)
                .HasColumnType("datetime")
                .HasColumnName("endTime");
            entity.Property(e => e.EventId)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("eventId");
            entity.Property(e => e.MaxParticipants).HasColumnName("maxParticipants");
            entity.Property(e => e.OrganizerId).HasColumnName("organizerId");
            entity.Property(e => e.StartTime)
                .HasColumnType("datetime")
                .HasColumnName("startTime");
            entity.Property(e => e.StatusId).HasColumnName("statusId");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasColumnName("title");
            entity.Property(e => e.TownshipId).HasColumnName("townshipId");
            entity.Property(e => e.Type)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("type");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("updatedAt");

            entity.HasOne(d => d.Status).WithMany(p => p.Events)
                .HasForeignKey(d => d.StatusId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Events__statusId__5A846E65");

            entity.HasOne(d => d.Township).WithMany(p => p.Events)
                .HasForeignKey(d => d.TownshipId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FK__Events__updatedA__59904A2C");
        });

        modelBuilder.Entity<EventImage>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__EventIma__3213E83F2758AC18");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("createdAt");
            entity.Property(e => e.EventId).HasColumnName("eventId");
            entity.Property(e => e.ImgName)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("imgName");
            entity.Property(e => e.IsPrimary).HasColumnName("isPrimary");
            entity.Property(e => e.MimeType)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("mimeType");

            entity.HasOne(d => d.Event).WithMany(p => p.EventImages)
                .HasForeignKey(d => d.EventId)
                .HasConstraintName("FK__EventImag__event__5F492382");

            entity.HasOne(d => d.File).WithMany(p => p.EventImages)
                .HasForeignKey(d => d.FileId)
                .HasConstraintName("FK__EventImag__FileI__5E54FF49");
        });

        modelBuilder.Entity<EventParticipant>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__EventPar__3213E83F14578DA5");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("createdAt");
            entity.Property(e => e.EventId).HasColumnName("eventId");
            entity.Property(e => e.IsCancel).HasColumnName("isCancel");
            entity.Property(e => e.NumberOfAttendees).HasColumnName("numberOfAttendees");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("updatedAt");
            entity.Property(e => e.UserId).HasColumnName("userId");

            entity.HasOne(d => d.Event).WithMany(p => p.EventParticipants)
                .HasForeignKey(d => d.EventId)
                .HasConstraintName("FK__EventPart__event__6501FCD8");

            entity.HasOne(d => d.User).WithMany(p => p.EventParticipants)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK__EventPart__updat__640DD89F");
        });

        modelBuilder.Entity<EventStatus>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__EventSta__3213E83F1086C707");

            entity.ToTable("EventStatus");

            entity.HasIndex(e => e.StatusCode, "UQ__EventSta__AD4366F6502C4A49").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("name");
            entity.Property(e => e.StatusCode)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("statusCode");
        });

        modelBuilder.Entity<ExternalLogin>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__External__3213E83FDBE8CF81");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("createdAt");
            entity.Property(e => e.Email)
                .HasMaxLength(256)
                .IsUnicode(false)
                .HasColumnName("email");
            entity.Property(e => e.LoginProvider)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("loginProvider");
            entity.Property(e => e.ProviderKey)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("providerKey");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("updatedAt");
            entity.Property(e => e.UserId).HasColumnName("userId");

            entity.HasOne(d => d.User).WithMany(p => p.ExternalLogins)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK__ExternalL__updat__69C6B1F5");
        });

        modelBuilder.Entity<Favorite>(entity =>
        {
            entity.HasKey(e => new { e.CustomerId, e.ProductId }).HasName("PK__Favorite__04C0C66B269017D8");

            entity.Property(e => e.CustomerId).HasColumnName("customerId");
            entity.Property(e => e.ProductId).HasColumnName("productId");
            entity.Property(e => e.FavoritedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("favoritedAt");

            entity.HasOne(d => d.Customer).WithMany(p => p.Favorites)
                .HasForeignKey(d => d.CustomerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Favorites__custo__42E1EEFE");

            entity.HasOne(d => d.Product).WithMany(p => p.Favorites)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Favorites__produ__43D61337");
        });

        modelBuilder.Entity<FeatureService>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__FeatureS__3213E83F2EEC23EF");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("isActive");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("name");

            entity.HasOne(d => d.File).WithMany(p => p.FeatureServices)
                .HasForeignKey(d => d.FileId)
                .HasConstraintName("FK__FeatureSe__FileI__00200768");
        });

        modelBuilder.Entity<FileStream>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__FileStre__3213E83FB9027428");

            entity.ToTable("FileStream");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.FileId).HasColumnName("fileId");
            entity.Property(e => e.FileName)
                .HasMaxLength(200)
                .HasColumnName("fileName");
        });

        modelBuilder.Entity<HealthCondition>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__HealthCo__3213E83FA39C5507");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("createdAt");
            entity.Property(e => e.Info)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("info");
            entity.Property(e => e.IsActive).HasColumnName("isActive");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("name");
            entity.Property(e => e.Type)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("type");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("updatedAt");
        });

        modelBuilder.Entity<Institution>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Institut__3213E83F908CE890");

            entity.HasIndex(e => e.InstitutionCode, "UQ__Institut__5BDD9EFDB1E185F9").IsUnique();

            entity.HasIndex(e => e.Email, "UQ__Institut__AB6E6164E82186CE").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Address)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("address");
            entity.Property(e => e.CityId).HasColumnName("cityId");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("createdAt");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(256)
                .IsUnicode(false)
                .HasColumnName("email");
            entity.Property(e => e.InstitutionCode)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("institutionCode");
            entity.Property(e => e.IsBanned).HasColumnName("isBanned");
            entity.Property(e => e.IsPhysicalCheck).HasColumnName("isPhysicalCheck");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("name");
            entity.Property(e => e.Phone)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("phone");
            entity.Property(e => e.PrincipalName)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("principalName");
            entity.Property(e => e.PrincipalPhone)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("principalPhone");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("status");
            entity.Property(e => e.TownshipId).HasColumnName("townshipId");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("updatedAt");

            entity.HasOne(d => d.City).WithMany(p => p.Institutions)
                .HasForeignKey(d => d.CityId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Instituti__cityI__10566F31");

            entity.HasOne(d => d.Township).WithMany(p => p.Institutions)
                .HasForeignKey(d => d.TownshipId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Instituti__towns__114A936A");
        });

        modelBuilder.Entity<InstitutionAuditImage>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Institut__3213E83F9EDE64ED");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("createdAt");
            entity.Property(e => e.ImgName)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("imgName");
            entity.Property(e => e.InstitutionId).HasColumnName("institutionId");
            entity.Property(e => e.MimeType)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("mimeType");

            entity.HasOne(d => d.File).WithMany(p => p.InstitutionAuditImages)
                .HasForeignKey(d => d.FileId)
                .HasConstraintName("FK__Instituti__FileI__3EDC53F0");

            entity.HasOne(d => d.Institution).WithMany(p => p.InstitutionAuditImages)
                .HasForeignKey(d => d.InstitutionId)
                .HasConstraintName("FK__Instituti__insti__3FD07829");
        });

        modelBuilder.Entity<InstitutionProfile>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Institut__3213E83F9EDEF61F");

            entity.HasIndex(e => e.UserId, "UQ__Institut__CB9A1CFE0CEBD1A6").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CreatedAt)
                .HasColumnType("datetime")
                .HasColumnName("createdAt");
            entity.Property(e => e.InstitutionId).HasColumnName("institutionId");
            entity.Property(e => e.IsResponsible).HasColumnName("isResponsible");
            entity.Property(e => e.Position)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("position");
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("datetime")
                .HasColumnName("updatedAt");
            entity.Property(e => e.UserId).HasColumnName("userId");

            entity.HasOne(d => d.Institution).WithMany(p => p.InstitutionProfiles)
                .HasForeignKey(d => d.InstitutionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Instituti__insti__7BE56230");

            entity.HasOne(d => d.User).WithOne(p => p.InstitutionProfile)
                .HasForeignKey<InstitutionProfile>(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Instituti__userI__7AF13DF7");
        });

        modelBuilder.Entity<Log>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Logs__3213E83FCE11648E");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("createdAt");
            entity.Property(e => e.Info)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("info");
            entity.Property(e => e.IpAddress)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("ipAddress");
            entity.Property(e => e.Type)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasColumnName("type");
            entity.Property(e => e.UserId).HasColumnName("userId");

            entity.HasOne(d => d.User).WithMany(p => p.Logs)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK__Logs__userId__6D9742D9");
        });

        modelBuilder.Entity<Media>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Medias__3213E83F97023B11");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.ContentId).HasColumnName("contentId");
            entity.Property(e => e.CreatedAt)
                .HasColumnType("datetime")
                .HasColumnName("createdAt");
            entity.Property(e => e.MediaTypeId).HasColumnName("mediaTypeId");
            entity.Property(e => e.MemberId).HasColumnName("memberId");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("name");
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("datetime")
                .HasColumnName("updatedAt");

            entity.HasOne(d => d.Content).WithMany(p => p.Media)
                .HasForeignKey(d => d.ContentId)
                .HasConstraintName("FK__Medias__contentI__76969D2E");

            entity.HasOne(d => d.File).WithMany(p => p.Media)
                .HasForeignKey(d => d.FileId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Medias__FileId__787EE5A0");

            entity.HasOne(d => d.MediaType).WithMany(p => p.Media)
                .HasForeignKey(d => d.MediaTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Medias__mediaTyp__778AC167");
        });

        modelBuilder.Entity<MediaType>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__MediaTyp__3213E83F0F136CA2");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CreatedAt)
                .HasColumnType("datetime")
                .HasColumnName("createdAt");
            entity.Property(e => e.IsEnabled).HasColumnName("isEnabled");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("name");
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("datetime")
                .HasColumnName("updatedAt");
        });

        modelBuilder.Entity<MemberProfile>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__MemberPr__3213E83F520B3A38");

            entity.HasIndex(e => e.UserId, "UQ__MemberPr__CB9A1CFE9D840301").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Address)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("address");
            entity.Property(e => e.CityId).HasColumnName("cityId");
            entity.Property(e => e.CreatedAt)
                .HasColumnType("datetime")
                .HasColumnName("createdAt");
            entity.Property(e => e.TownshipId).HasColumnName("townshipId");
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("datetime")
                .HasColumnName("updatedAt");
            entity.Property(e => e.UserId).HasColumnName("userId");

            entity.HasOne(d => d.City).WithMany(p => p.MemberProfiles)
                .HasForeignKey(d => d.CityId)
                .HasConstraintName("FK__MemberPro__cityI__725BF7F6");

            entity.HasOne(d => d.Township).WithMany(p => p.MemberProfiles)
                .HasForeignKey(d => d.TownshipId)
                .HasConstraintName("FK__MemberPro__towns__73501C2F");

            entity.HasOne(d => d.User).WithOne(p => p.MemberProfile)
                .HasForeignKey<MemberProfile>(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__MemberPro__userI__7167D3BD");
        });

        modelBuilder.Entity<Notify>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Notifys__3213E83FC02E95AD");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CategoriesId).HasColumnName("categoriesId");
            entity.Property(e => e.NotifysUrl)
                .HasMaxLength(500)
                .HasColumnName("notifysUrl");
            entity.Property(e => e.SendDate)
                .HasColumnType("datetime")
                .HasColumnName("sendDate");
            entity.Property(e => e.Text)
                .HasMaxLength(500)
                .HasColumnName("text");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("title");
            entity.Property(e => e.ValidityDate)
                .HasColumnType("datetime")
                .HasColumnName("validityDate");

            entity.HasOne(d => d.Categories).WithMany(p => p.Notifies)
                .HasForeignKey(d => d.CategoriesId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Notifys__categor__534D60F1");
        });

        modelBuilder.Entity<NotifyUser>(entity =>
        {
            entity.HasKey(e => new { e.NotifyId, e.UserId }).HasName("PK__NotifyUs__56C75409A12E651E");

            entity.Property(e => e.NotifyId).HasColumnName("notifyId");
            entity.Property(e => e.UserId).HasColumnName("userId");
            entity.Property(e => e.IsRead).HasColumnName("isRead");

            entity.HasOne(d => d.Notify).WithMany(p => p.NotifyUsers)
                .HasForeignKey(d => d.NotifyId)
                .HasConstraintName("FK__NotifyUse__notif__6383C8BA");

            entity.HasOne(d => d.User).WithMany(p => p.NotifyUsers)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK__NotifyUse__userI__628FA481");
        });

        modelBuilder.Entity<NotifysCategory>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__NotifysC__3213E83F15068334");

            entity.ToTable("NotifysCategory");

            entity.HasIndex(e => e.Name, "UQ__NotifysC__72E12F1BABF76F16").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Enable)
                .HasDefaultValue(true)
                .HasColumnName("enable");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("name");
        });

        modelBuilder.Entity<Order>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Orders__3213E83F9AF1BD7B");

            entity.ToTable(tb => tb.HasTrigger("TR_Orders_UpdateAt"));

            entity.HasIndex(e => e.OrderNumber, "UQ__Orders__6296129FC0AAE91A").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CouponDiscount)
                .HasDefaultValue(0m)
                .HasColumnType("decimal(18, 0)")
                .HasColumnName("couponDiscount");
            entity.Property(e => e.CouponId).HasColumnName("couponId");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("createdAt");
            entity.Property(e => e.CustomerId).HasColumnName("customerId");
            entity.Property(e => e.Note)
                .HasMaxLength(1000)
                .HasColumnName("note");
            entity.Property(e => e.OrderNumber)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("orderNumber");
            entity.Property(e => e.ShippingFee)
                .HasColumnType("decimal(18, 0)")
                .HasColumnName("shippingFee");
            entity.Property(e => e.SubtotalAmount)
                .HasColumnType("decimal(18, 0)")
                .HasColumnName("subtotalAmount");
            entity.Property(e => e.TotalAmount)
                .HasColumnType("decimal(18, 0)")
                .HasColumnName("totalAmount");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("updatedAt");

            entity.HasOne(d => d.Coupon).WithMany(p => p.Orders)
                .HasForeignKey(d => d.CouponId)
                .HasConstraintName("FK__Orders__couponId__7755B73D");

            entity.HasOne(d => d.Customer).WithMany(p => p.Orders)
                .HasForeignKey(d => d.CustomerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Orders__customer__756D6ECB");
        });

        modelBuilder.Entity<OrderItem>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__OrderIte__3213E83F1C4425D8");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.OrderId).HasColumnName("orderId");
            entity.Property(e => e.ProductId).HasColumnName("productId");
            entity.Property(e => e.ProductName)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("productName");
            entity.Property(e => e.Quantity).HasColumnName("quantity");
            entity.Property(e => e.Subtotal)
                .HasColumnType("decimal(18, 0)")
                .HasColumnName("subtotal");
            entity.Property(e => e.UnitPrice)
                .HasColumnType("decimal(18, 0)")
                .HasColumnName("unitPrice");

            entity.HasOne(d => d.Order).WithMany(p => p.OrderItems)
                .HasForeignKey(d => d.OrderId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__OrderItem__order__03BB8E22");

            entity.HasOne(d => d.Product).WithMany(p => p.OrderItems)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__OrderItem__produ__04AFB25B");
        });

        modelBuilder.Entity<OrderRecipent>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__OrderRec__3213E83FEB0A09C2");

            entity.HasIndex(e => e.OrderId, "UQ__OrderRec__0809335C077FCE0B").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.OrderId).HasColumnName("orderId");
            entity.Property(e => e.RecipentName)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("recipentName");
            entity.Property(e => e.RecipentPhone)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("recipentPhone");

            entity.HasOne(d => d.Order).WithOne(p => p.OrderRecipent)
                .HasForeignKey<OrderRecipent>(d => d.OrderId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__OrderReci__order__0880433F");
        });

        modelBuilder.Entity<OrderShipMethod>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__OrderShi__3213E83FDB9307A2");

            entity.ToTable("OrderShipMethod");

            entity.HasIndex(e => e.OrderId, "UQ__OrderShi__0809335C00B362C2").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CarrierCode)
                .HasMaxLength(50)
                .HasColumnName("carrierCode");
            entity.Property(e => e.CityId).HasColumnName("cityId");
            entity.Property(e => e.CreatedAt)
                .HasColumnType("datetime")
                .HasColumnName("createdAt");
            entity.Property(e => e.DetailAddress)
                .HasMaxLength(1000)
                .HasColumnName("detailAddress");
            entity.Property(e => e.HomeTrackingCode)
                .HasMaxLength(100)
                .HasColumnName("homeTrackingCode");
            entity.Property(e => e.OrderId).HasColumnName("orderId");
            entity.Property(e => e.ShipId).HasColumnName("shipId");
            entity.Property(e => e.StoreAddress)
                .HasMaxLength(250)
                .HasColumnName("storeAddress");
            entity.Property(e => e.StoreCode)
                .HasMaxLength(50)
                .HasColumnName("storeCode");
            entity.Property(e => e.StoreTrackingCode)
                .HasMaxLength(100)
                .HasColumnName("storeTrackingCode");
            entity.Property(e => e.TownshipId).HasColumnName("townshipId");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("updatedAt");

            entity.HasOne(d => d.City).WithMany(p => p.OrderShipMethods)
                .HasForeignKey(d => d.CityId)
                .HasConstraintName("FK__OrderShip__cityI__1209AD79");

            entity.HasOne(d => d.Order).WithOne(p => p.OrderShipMethod)
                .HasForeignKey<OrderShipMethod>(d => d.OrderId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__OrderShip__order__10216507");

            entity.HasOne(d => d.Ship).WithMany(p => p.OrderShipMethods)
                .HasForeignKey(d => d.ShipId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__OrderShip__shipI__11158940");

            entity.HasOne(d => d.Township).WithMany(p => p.OrderShipMethods)
                .HasForeignKey(d => d.TownshipId)
                .HasConstraintName("FK__OrderShip__towns__12FDD1B2");
        });

        modelBuilder.Entity<OrderStatus>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__OrderSta__3213E83F5EB70ABA");

            entity.ToTable("OrderStatus");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("createdAt");
            entity.Property(e => e.OrderId).HasColumnName("orderId");
            entity.Property(e => e.OrderStatusItemId).HasColumnName("orderStatusItemId");

            entity.HasOne(d => d.Order).WithMany(p => p.OrderStatuses)
                .HasForeignKey(d => d.OrderId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__OrderStat__order__0B5CAFEA");

            entity.HasOne(d => d.OrderStatusItem).WithMany(p => p.OrderStatuses)
                .HasForeignKey(d => d.OrderStatusItemId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OrderStatus_OrderStatusItem");
        });

        modelBuilder.Entity<OrderStatusItem>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__OrederSt__3213E83F7790D53E");

            entity.ToTable("OrderStatusItem");

            entity.HasIndex(e => e.Name, "UQ__OrederSt__72E12F1B1C823B18").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("name");
        });

        modelBuilder.Entity<Organization>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Organiza__3213E83F8ED3F5D0");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Address)
                .HasMaxLength(100)
                .HasColumnName("address");
            entity.Property(e => e.AgeLimits)
                .HasMaxLength(100)
                .HasColumnName("ageLimits");
            entity.Property(e => e.BedCount).HasColumnName("bedCount");
            entity.Property(e => e.CityId).HasColumnName("cityId");
            entity.Property(e => e.Description)
                .HasMaxLength(100)
                .HasColumnName("description");
            entity.Property(e => e.DistrictId).HasColumnName("districtId");
            entity.Property(e => e.InstitutionId).HasColumnName("institutionId");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("isActive");
            entity.Property(e => e.IsCertified).HasColumnName("isCertified");
            entity.Property(e => e.IsDeleted).HasColumnName("isDeleted");
            entity.Property(e => e.IsRecommended).HasColumnName("isRecommended");
            entity.Property(e => e.MapUrl)
                .HasMaxLength(100)
                .HasColumnName("mapUrl");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("name");
            entity.Property(e => e.PhotoUrl)
                .HasMaxLength(100)
                .HasColumnName("photoUrl");
            entity.Property(e => e.TypeId).HasColumnName("typeId");

            entity.HasOne(d => d.City).WithMany(p => p.Organizations)
                .HasForeignKey(d => d.CityId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Organizat__cityI__14270015");

            entity.HasOne(d => d.District).WithMany(p => p.Organizations)
                .HasForeignKey(d => d.DistrictId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Organizat__distr__151B244E");

            entity.HasOne(d => d.Institution).WithMany(p => p.Organizations)
                .HasForeignKey(d => d.InstitutionId)
                .HasConstraintName("FK__Organizat__insti__18EBB532");

            entity.HasOne(d => d.Type).WithMany(p => p.Organizations)
                .HasForeignKey(d => d.TypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Organizat__typeI__160F4887");
        });

        modelBuilder.Entity<OrganizationCertificationRequest>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Organiza__3213E83F86297A71");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.ApprovedAt)
                .HasColumnType("datetime")
                .HasColumnName("approvedAt");
            entity.Property(e => e.OrganizationId).HasColumnName("organizationId");
            entity.Property(e => e.RejectionReason).HasColumnName("rejectionReason");
            entity.Property(e => e.ReviewerId).HasColumnName("reviewerId");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("status");
            entity.Property(e => e.SubmittedAt)
                .HasColumnType("datetime")
                .HasColumnName("submittedAt");

            entity.HasOne(d => d.Organization).WithMany(p => p.OrganizationCertificationRequests)
                .HasForeignKey(d => d.OrganizationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Organizat__organ__1F98B2C1");
        });

        modelBuilder.Entity<OrganizationFeatureService>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Organiza__3213E83F2378C5D7");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.FeatureServiceId).HasColumnName("featureServiceId");
            entity.Property(e => e.OrganizationId).HasColumnName("organizationId");

            entity.HasOne(d => d.FeatureService).WithMany(p => p.OrganizationFeatureServices)
                .HasForeignKey(d => d.FeatureServiceId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Organizat__featu__236943A5");

            entity.HasOne(d => d.Organization).WithMany(p => p.OrganizationFeatureServices)
                .HasForeignKey(d => d.OrganizationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Organizat__organ__22751F6C");
        });

        modelBuilder.Entity<OrganizationRoom>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Organiza__3213E83F7B7C5756");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.DepositAmount).HasColumnName("depositAmount");
            entity.Property(e => e.DepositMonths)
                .HasColumnType("decimal(3, 1)")
                .HasColumnName("depositMonths");
            entity.Property(e => e.HasDeposit).HasColumnName("hasDeposit");
            entity.Property(e => e.MonthlyPrice).HasColumnName("monthlyPrice");
            entity.Property(e => e.OrganizationId).HasColumnName("organizationId");
            entity.Property(e => e.RoomQuantity).HasColumnName("roomQuantity");
            entity.Property(e => e.RoomTypeId).HasColumnName("roomTypeId");

            entity.HasOne(d => d.Organization).WithMany(p => p.OrganizationRooms)
                .HasForeignKey(d => d.OrganizationId)
                .HasConstraintName("FK__Organizat__organ__2645B050");

            entity.HasOne(d => d.RoomType).WithMany(p => p.OrganizationRooms)
                .HasForeignKey(d => d.RoomTypeId)
                .HasConstraintName("FK__Organizat__roomT__2739D489");
        });

        modelBuilder.Entity<OrganizationServiceTarget>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Organiza__3213E83FDE0D4890");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.OrganizationId).HasColumnName("organizationId");
            entity.Property(e => e.ServiceTargetId).HasColumnName("serviceTargetId");

            entity.HasOne(d => d.Organization).WithMany(p => p.OrganizationServiceTargets)
                .HasForeignKey(d => d.OrganizationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Organizat__organ__2A164134");

            entity.HasOne(d => d.ServiceTarget).WithMany(p => p.OrganizationServiceTargets)
                .HasForeignKey(d => d.ServiceTargetId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Organizat__servi__2B0A656D");
        });

        modelBuilder.Entity<OrganizationSubsidyInfo>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Organiza__3213E83F064911B6");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.OrganizationId).HasColumnName("organizationId");
            entity.Property(e => e.SubsidyInfoId).HasColumnName("subsidyInfoId");

            entity.HasOne(d => d.Organization).WithMany(p => p.OrganizationSubsidyInfos)
                .HasForeignKey(d => d.OrganizationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Organizat__organ__1BC821DD");

            entity.HasOne(d => d.SubsidyInfo).WithMany(p => p.OrganizationSubsidyInfos)
                .HasForeignKey(d => d.SubsidyInfoId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Organizat__subsi__1CBC4616");
        });

        modelBuilder.Entity<OrganizationType>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Organiza__3213E83FF4A97C87");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("name");
        });

        modelBuilder.Entity<Payment>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Payment__3213E83F62BCE249");

            entity.ToTable("Payment", tb => tb.HasTrigger("TR_Payment_UpdateAt"));

            entity.HasIndex(e => e.OrderId, "UQ__Payment__0809335C97CE33D7").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Amount)
                .HasColumnType("decimal(18, 0)")
                .HasColumnName("amount");
            entity.Property(e => e.CreatAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("creatAt");
            entity.Property(e => e.OrderId).HasColumnName("orderId");
            entity.Property(e => e.PaidAt)
                .HasColumnType("datetime")
                .HasColumnName("paidAt");
            entity.Property(e => e.PayMethodId).HasColumnName("payMethodId");
            entity.Property(e => e.Status).HasColumnName("status");
            entity.Property(e => e.TransactionId)
                .HasMaxLength(100)
                .HasColumnName("transactionId");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("updatedAt");

            entity.HasOne(d => d.Order).WithOne(p => p.Payment)
                .HasForeignKey<Payment>(d => d.OrderId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Payment__orderId__17C286CF");

            entity.HasOne(d => d.PayMethod).WithMany(p => p.Payments)
                .HasForeignKey(d => d.PayMethodId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Payment__payMeth__18B6AB08");

            entity.HasOne(d => d.StatusNavigation).WithMany(p => p.Payments)
                .HasForeignKey(d => d.Status)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Payment_paymentStaus");
        });

        modelBuilder.Entity<PaymentMethod>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__PaymentM__3213E83FE9116208");

            entity.HasIndex(e => e.Name, "UQ__PaymentM__72E12F1B52F61D51").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("isActive");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("name");
        });

        modelBuilder.Entity<PaymentStatus>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_paymentStaus");

            entity.ToTable("paymentStatus");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("name");
        });

        modelBuilder.Entity<Permission>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Permissi__3213E83F4661C52E");

            entity.HasIndex(e => e.PermissionCode, "UQ__Permissi__DF6AE8FFAB771C90").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("createdAt");
            entity.Property(e => e.DeprecatedAt)
                .HasColumnType("datetime")
                .HasColumnName("deprecatedAt");
            entity.Property(e => e.Info)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("info");
            entity.Property(e => e.IsActive).HasColumnName("isActive");
            entity.Property(e => e.IsSystemDefault).HasColumnName("isSystemDefault");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("name");
            entity.Property(e => e.PermissionCode)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("permissionCode");
            entity.Property(e => e.PermissionType)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasColumnName("permissionType");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("updatedAt");
        });

        modelBuilder.Entity<Plate>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Plate__3213E83F26238E1A");

            entity.ToTable("Plate");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.DefaultImageClickUrl)
                .HasMaxLength(500)
                .HasColumnName("defaultImageClickUrl");
            entity.Property(e => e.DefaultImageFileId).HasColumnName("defaultImageFileId");
            entity.Property(e => e.DefaultImageIntroduct)
                .HasMaxLength(50)
                .HasColumnName("defaultImageIntroduct");
            entity.Property(e => e.Enable).HasDefaultValue(true);
            entity.Property(e => e.Location)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Route)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.DefaultImageFile).WithMany(p => p.Plates)
                .HasForeignKey(d => d.DefaultImageFileId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Plate__defaultIm__6754599E");
        });

        modelBuilder.Entity<PlateImage>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__PlateIma__3213E83FBFDA0B7E");

            entity.ToTable("PlateImage");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.ClickNumber).HasColumnName("clickNumber");
            entity.Property(e => e.ClickUrl)
                .HasMaxLength(500)
                .HasColumnName("clickUrl");
            entity.Property(e => e.DisplayOrder).HasColumnName("displayOrder");
            entity.Property(e => e.EndDate).HasColumnName("endDate");
            entity.Property(e => e.ImageFileId).HasColumnName("imageFileId");
            entity.Property(e => e.Introduct)
                .HasMaxLength(50)
                .HasColumnName("introduct");
            entity.Property(e => e.PlateId).HasColumnName("plateId");
            entity.Property(e => e.StartDate).HasColumnName("startDate");

            entity.HasOne(d => d.ImageFile).WithMany(p => p.PlateImages)
                .HasForeignKey(d => d.ImageFileId)
                .HasConstraintName("FK__PlateImag__image__6A30C649");

            entity.HasOne(d => d.Plate).WithMany(p => p.PlateImages)
                .HasForeignKey(d => d.PlateId)
                .HasConstraintName("FK__PlateImag__plate__6B24EA82");
        });

        modelBuilder.Entity<Product>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Products__3213E83F00E241F4");

            entity.ToTable(tb => tb.HasTrigger("TR_products_UpdateAt"));

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CreateAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("createAt");
            entity.Property(e => e.IsActive).HasColumnName("isActive");
            entity.Property(e => e.ItemNumber)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("itemNumber");
            entity.Property(e => e.Keypoint)
                .IsRequired()
                .HasMaxLength(250)
                .HasColumnName("keypoint");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("name");
            entity.Property(e => e.Price)
                .HasColumnType("decimal(18, 0)")
                .HasColumnName("price");
            entity.Property(e => e.ProductDescription)
                .IsRequired()
                .HasColumnName("productDescription");
            entity.Property(e => e.Quantity).HasColumnName("quantity");
            entity.Property(e => e.UpdateAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("updateAt");
        });

        modelBuilder.Entity<ProductCategory>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__ProductC__3213E83F4F410023");

            entity.HasIndex(e => new { e.ProductId, e.CategoryId }, "UQ__ProductC__BF2C7E761C44C7EF").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CategoryId).HasColumnName("categoryId");
            entity.Property(e => e.ProductId).HasColumnName("productId");

            entity.HasOne(d => d.Category).WithMany(p => p.ProductCategories)
                .HasForeignKey(d => d.CategoryId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ProductCa__categ__607251E5");

            entity.HasOne(d => d.Product).WithMany(p => p.ProductCategories)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ProductCa__produ__5F7E2DAC");
        });

        modelBuilder.Entity<ProductImage>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__ProductI__3213E83FAE3C5033");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.ProductId).HasColumnName("productId");
            entity.Property(e => e.SortOrder)
                .HasDefaultValue(2)
                .HasColumnName("sortOrder");

            entity.HasOne(d => d.File).WithMany(p => p.ProductImages)
                .HasForeignKey(d => d.FileId)
                .HasConstraintName("FK__ProductIm__FileI__65370702");

            entity.HasOne(d => d.Product).WithMany(p => p.ProductImages)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ProductIm__produ__634EBE90");
        });

        modelBuilder.Entity<ProductNote>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__ProductN__3213E83F91820F90");

            entity.ToTable("ProductNote");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("createdAt");
            entity.Property(e => e.DeliveryAndPayMethod).HasColumnName("deliveryAndPayMethod");
            entity.Property(e => e.ShoppNote).HasColumnName("shoppNote");
        });

        modelBuilder.Entity<ProductShip>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__ProductS__3213E83FA209AC19");

            entity.HasIndex(e => new { e.ProductId, e.ShipId }, "UQ__ProductS__61D8A2D7124D99C7").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.IsActive).HasColumnName("isActive");
            entity.Property(e => e.ProductId).HasColumnName("productId");
            entity.Property(e => e.ShipId).HasColumnName("shipId");

            entity.HasOne(d => d.Product).WithMany(p => p.ProductShips)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ProductSh__produ__59C55456");

            entity.HasOne(d => d.Ship).WithMany(p => p.ProductShips)
                .HasForeignKey(d => d.ShipId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ProductSh__shipI__5AB9788F");
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Roles__3213E83F21B30355");

            entity.HasIndex(e => e.RoleCode, "UQ__Roles__44FD4F90A1D7FC86").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("createdAt");
            entity.Property(e => e.Info)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("info");
            entity.Property(e => e.IsActive).HasColumnName("isActive");
            entity.Property(e => e.IsSystemDefault).HasColumnName("isSystemDefault");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("name");
            entity.Property(e => e.RoleCode)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("roleCode");
            entity.Property(e => e.RoleType)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasColumnName("roleType");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("updatedAt");
        });

        modelBuilder.Entity<RolePermission>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__RolePerm__3213E83F2DB3196E");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("createdAt");
            entity.Property(e => e.PermissionId).HasColumnName("permissionId");
            entity.Property(e => e.RoleId).HasColumnName("roleId");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("updatedAt");

            entity.HasOne(d => d.Permission).WithMany(p => p.RolePermissions)
                .HasForeignKey(d => d.PermissionId)
                .HasConstraintName("FK__RolePermi__permi__29E1370A");

            entity.HasOne(d => d.Role).WithMany(p => p.RolePermissions)
                .HasForeignKey(d => d.RoleId)
                .HasConstraintName("FK__RolePermi__roleI__28ED12D1");
        });

        modelBuilder.Entity<RoomType>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__RoomType__3213E83FA176B7BA");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("name");
        });

        modelBuilder.Entity<ServiceTarget>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__ServiceT__3213E83FE758A0E4");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("isActive");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("name");
        });

        modelBuilder.Entity<Ship>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Ships__3213E83FCAD675E4");

            entity.HasIndex(e => e.ShipMethodName, "UQ__Ships__DC90D6A130B5E5E7").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("isActive");
            entity.Property(e => e.ShipCost)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("shipCost");
            entity.Property(e => e.ShipMethodName)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("shipMethodName");
        });

        modelBuilder.Entity<ShippingRule>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Shipping__3213E83FE576AFED");

            entity.ToTable(tb => tb.HasTrigger("TR_ShippingRules_UpdateAt"));

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CreateAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("createAt");
            entity.Property(e => e.EndAt)
                .HasColumnType("datetime")
                .HasColumnName("endAt");
            entity.Property(e => e.IsActive).HasColumnName("isActive");
            entity.Property(e => e.MiniOrderAmout).HasColumnName("miniOrderAmout");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("name");
            entity.Property(e => e.StartAt)
                .HasColumnType("datetime")
                .HasColumnName("startAt");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("updatedAt");
        });

        modelBuilder.Entity<ShopHomePageBanner>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__ShopHome__3213E83F8FEA6155");

            entity.ToTable(tb => tb.HasTrigger("trg_ShopHomePageBanners_Updated"));

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CreateAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("createAt");
            entity.Property(e => e.IsActive)
                .HasDefaultValue(true)
                .HasColumnName("isActive");
            entity.Property(e => e.LandingPageUrl).HasColumnName("landingPageUrl");
            entity.Property(e => e.Position).HasColumnName("position");
            entity.Property(e => e.ShopBannerUrl)
                .IsRequired()
                .HasColumnName("shopBannerUrl");
            entity.Property(e => e.Updated)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("updated");
        });

        modelBuilder.Entity<SubsidyInfo>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__SubsidyI__3213E83FF548AF09");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("description");
        });

        modelBuilder.Entity<Township>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Township__3213E83F578E5612");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CityId).HasColumnName("cityId");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("name");
            entity.Property(e => e.PostalCode)
                .IsRequired()
                .HasMaxLength(6)
                .IsUnicode(false)
                .HasColumnName("postalCode");

            entity.HasOne(d => d.City).WithMany(p => p.Townships)
                .HasForeignKey(d => d.CityId)
                .HasConstraintName("FK__Townships__cityI__59063A47");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Users__3213E83F3BB2E402");

            entity.HasIndex(e => new { e.Email, e.AccountType }, "UQ__Users__C98484590D2FCEF6").IsUnique();

            entity.HasIndex(e => e.UserId, "UQ__Users__CB9A1CFED99D2BE0").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.AccountType)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasColumnName("accountType");
            entity.Property(e => e.ConfirmCode)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("confirmCode");
            entity.Property(e => e.ConfirmCodeExpiresAt)
                .HasColumnType("datetime")
                .HasColumnName("confirmCodeExpiresAt");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("createdAt");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(256)
                .IsUnicode(false)
                .HasColumnName("email");
            entity.Property(e => e.FailedLoginCount).HasColumnName("failedLoginCount");
            entity.Property(e => e.LastLoginAt)
                .HasColumnType("datetime")
                .HasColumnName("lastLoginAt");
            entity.Property(e => e.LockedUntil)
                .HasColumnType("datetime")
                .HasColumnName("lockedUntil");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("name");
            entity.Property(e => e.Password)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("password");
            entity.Property(e => e.Phone)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("phone");
            entity.Property(e => e.ResetPasswordConfirmCode)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("resetPasswordConfirmCode");
            entity.Property(e => e.ResetPasswordConfirmCodeExpiresAt)
                .HasColumnType("datetime")
                .HasColumnName("resetPasswordConfirmCodeExpiresAt");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("status");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("updatedAt");
            entity.Property(e => e.UserId)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("userId");
        });

        modelBuilder.Entity<UserCareRecipient>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__UserCare__3213E83F4A856FB6");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CareRecipientId).HasColumnName("careRecipientId");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("createdAt");
            entity.Property(e => e.PermissionLevel)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasColumnName("permissionLevel");
            entity.Property(e => e.Relationship)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("relationship");
            entity.Property(e => e.UserId).HasColumnName("userId");

            entity.HasOne(d => d.CareRecipient).WithMany(p => p.UserCareRecipients)
                .HasForeignKey(d => d.CareRecipientId)
                .HasConstraintName("FK__UserCareR__careR__3552E9B6");

            entity.HasOne(d => d.User).WithMany(p => p.UserCareRecipients)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK__UserCareR__userI__345EC57D");
        });

        modelBuilder.Entity<UserRole>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__UserRole__3213E83F2FF882F3");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("createdAt");
            entity.Property(e => e.RoleId).HasColumnName("roleId");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("updatedAt");
            entity.Property(e => e.UserId).HasColumnName("userId");

            entity.HasOne(d => d.Role).WithMany(p => p.UserRoles)
                .HasForeignKey(d => d.RoleId)
                .HasConstraintName("FK__UserRoles__updat__3A179ED3");

            entity.HasOne(d => d.User).WithMany(p => p.UserRoles)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK__UserRoles__userI__3B0BC30C");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}