// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Team1.VitalBridge.Frontend.Models.EFModels;

public partial class CareRecipientsImage
{
    public int Id { get; set; }

    public int CareRecipientId { get; set; }

    public string ImgName { get; set; }

    public string MimeType { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public int? FileId { get; set; }

    public virtual CareRecipient CareRecipient { get; set; }

    public virtual FileStream File { get; set; }
}