// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Team1.VitalBridge.Frontend.Models.EFModels;

public partial class CareRecipient
{
    public int Id { get; set; }

    public string CareRecipientId { get; set; }

    public string Name { get; set; }

    public string Gender { get; set; }

    public DateOnly BirthDate { get; set; }

    public int Height { get; set; }

    public int Weight { get; set; }

    public string Phone { get; set; }

    public int? CityId { get; set; }

    public int? TownshipId { get; set; }

    public string Address { get; set; }

    public int CareLevel { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ICollection<CareRecipientHealthCondition> CareRecipientHealthConditions { get; set; } = new List<CareRecipientHealthCondition>();

    public virtual ICollection<CareRecipientInvitation> CareRecipientInvitations { get; set; } = new List<CareRecipientInvitation>();

    public virtual ICollection<CareRecipientsImage> CareRecipientsImages { get; set; } = new List<CareRecipientsImage>();

    public virtual City City { get; set; }

    public virtual ICollection<EmergencyContact> EmergencyContacts { get; set; } = new List<EmergencyContact>();

    public virtual Township Township { get; set; }

    public virtual ICollection<UserCareRecipient> UserCareRecipients { get; set; } = new List<UserCareRecipient>();
}