// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Team1.VitalBridge.Frontend.Models.EFModels;

public partial class CareRecipientInvitation
{
    public int Id { get; set; }

    public int InviterUserId { get; set; }

    public int CareRecipientId { get; set; }

    public string InviteeEmail { get; set; }

    public string Status { get; set; }

    public string PermissionLevel { get; set; }

    public string ConfirmCode { get; set; }

    public DateTime? ConfirmCodeExpiresAt { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public DateTime? RespondedAt { get; set; }

    public virtual CareRecipient CareRecipient { get; set; }

    public virtual User InviterUser { get; set; }
}