// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Team1.VitalBridge.Frontend.Models.EFModels;

public partial class CareRecipientHealthCondition
{
    public int Id { get; set; }

    public int CareRecipientId { get; set; }

    public int HealthConditionsId { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual CareRecipient CareRecipient { get; set; }

    public virtual HealthCondition HealthConditions { get; set; }
}