// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Team1.VitalBridge.Frontend.Models.EFModels;

public partial class CareRecipientHealthCondition
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("careRecipientId")]
    public int CareRecipientId { get; set; }

    [Column("healthConditionsId")]
    public int HealthConditionsId { get; set; }

    [Column("createdAt", TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [ForeignKey("CareRecipientId")]
    [InverseProperty("CareRecipientHealthConditions")]
    public virtual CareRecipient CareRecipient { get; set; }

    [ForeignKey("HealthConditionsId")]
    [InverseProperty("CareRecipientHealthConditions")]
    public virtual HealthCondition HealthConditions { get; set; }
}