// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Team1.VitalBridge.Frontend.Models.EFModels;

public partial class Category
{
    public int Id { get; set; }

    public int? FatherId { get; set; }

    public string Name { get; set; }

    public bool IsActive { get; set; }

    public int? FileId { get; set; }

    public virtual Category Father { get; set; }

    public virtual FileStream File { get; set; }

    public virtual ICollection<Category> InverseFather { get; set; } = new List<Category>();

    public virtual ICollection<ProductCategory> ProductCategories { get; set; } = new List<ProductCategory>();
}