// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Team1.VitalBridge.Frontend.Models.EFModels;

public partial class Comment
{
    public int Id { get; set; }

    public int MemberId { get; set; }

    public int ContentId { get; set; }

    public int? ParentCommentId { get; set; }

    public string Content { get; set; }

    public bool IsEnabled { get; set; }

    public DateTime UpdatedAt { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Content ContentNavigation { get; set; }

    public virtual ICollection<Comment> InverseParentComment { get; set; } = new List<Comment>();

    public virtual Comment ParentComment { get; set; }
}