// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Team1.VitalBridge.Frontend.Models.EFModels;

public partial class Content
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("memberId")]
    public int MemberId { get; set; }

    [Column("contentCategoryId")]
    public int ContentCategoryId { get; set; }

    [Required]
    [Column("title")]
    [StringLength(50)]
    public string Title { get; set; }

    [Column("coverPic")]
    public byte[] CoverPic { get; set; }

    [Required]
    [Column("content")]
    public string Content1 { get; set; }

    [Column("status")]
    public int Status { get; set; }

    [Column("viewCount")]
    public int ViewCount { get; set; }

    [Column("updatedAt", TypeName = "datetime")]
    public DateTime UpdatedAt { get; set; }

    [Column("createdAt", TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [Column("coverPicFileId")]
    public int? CoverPicFileId { get; set; }

    [InverseProperty("ContentNavigation")]
    public virtual ICollection<Comment> Comments { get; set; } = new List<Comment>();

    [ForeignKey("ContentCategoryId")]
    [InverseProperty("Contents")]
    public virtual ContentCategory ContentCategory { get; set; }

    [ForeignKey("CoverPicFileId")]
    [InverseProperty("Contents")]
    public virtual FileStream CoverPicFile { get; set; }

    [InverseProperty("Content")]
    public virtual ICollection<Media> Media { get; set; } = new List<Media>();

    [ForeignKey("MemberId")]
    [InverseProperty("Contents")]
    public virtual User Member { get; set; }
}