// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Team1.VitalBridge.Frontend.Models.EFModels;

public partial class Content
{
    public int Id { get; set; }

    public int MemberId { get; set; }

    public int ContentCategoryId { get; set; }

    public string Title { get; set; }

    public byte[] CoverPic { get; set; }

    public string Content1 { get; set; }

    public int Status { get; set; }

    public int ViewCount { get; set; }

    public DateTime UpdatedAt { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ICollection<Comment> Comments { get; set; } = new List<Comment>();

    public virtual ContentCategory ContentCategory { get; set; }

    public virtual ICollection<Media> Media { get; set; } = new List<Media>();
}