// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Team1.VitalBridge.Frontend.Models.EFModels;

public partial class CouponRecord
{
    public int Id { get; set; }

    public int CustomerId { get; set; }

    public int CoupounId { get; set; }

    public string CouponCode { get; set; }

    public decimal DiscountAmount { get; set; }

    public int OrderId { get; set; }

    public decimal OrderAmount { get; set; }

    public DateTime CeatedAt { get; set; }

    public virtual Coupon Coupoun { get; set; }

    public virtual User Customer { get; set; }

    public virtual Order Order { get; set; }
}