// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Team1.VitalBridge.Frontend.Models.EFModels;

public partial class Coupon
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string CouponCode { get; set; }

    public DateTime StartAt { get; set; }

    public DateTime EndAt { get; set; }

    public decimal Discount { get; set; }

    public decimal MinOrderCost { get; set; }

    public int UseageLimit { get; set; }

    public int CanUseCount { get; set; }

    public bool IsActive { get; set; }

    public int? UsedCount { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ICollection<CouponRecord> CouponRecords { get; set; } = new List<CouponRecord>();

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}