// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Team1.VitalBridge.Frontend.Models.EFModels;

public partial class Event
{
    public int Id { get; set; }

    public string EventId { get; set; }

    public string Type { get; set; }

    public int OrganizerId { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string Details { get; set; }

    public int? CityId { get; set; }

    public int? TownshipId { get; set; }

    public string Address { get; set; }

    public int StatusId { get; set; }

    public DateTime StartTime { get; set; }

    public DateTime EndTime { get; set; }

    public int MaxParticipants { get; set; }

    public int CurrentParticipants { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ICollection<EventImage> EventImages { get; set; } = new List<EventImage>();

    public virtual ICollection<EventParticipant> EventParticipants { get; set; } = new List<EventParticipant>();

    public virtual EventStatus Status { get; set; }

    public virtual Township Township { get; set; }
}