// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Team1.VitalBridge.Frontend.Models.EFModels;

public partial class EventParticipant
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public int EventId { get; set; }

    public int NumberOfAttendees { get; set; }

    public bool IsCancel { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual Event Event { get; set; }

    public virtual User User { get; set; }
}