// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Team1.VitalBridge.Frontend.Models.EFModels;

public partial class Favorite
{
    public int CustomerId { get; set; }

    public int ProductId { get; set; }

    public DateTime? FavoritedAt { get; set; }

    public virtual User Customer { get; set; }

    public virtual Product Product { get; set; }
}