// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Team1.VitalBridge.Frontend.Models.EFModels;

public partial class FeatureService
{
    public int Id { get; set; }

    public string Name { get; set; }

    public bool IsActive { get; set; }

    public int? FileId { get; set; }

    public virtual FileStream File { get; set; }

    public virtual ICollection<OrganizationFeatureService> OrganizationFeatureServices { get; set; } = new List<OrganizationFeatureService>();
}