// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Team1.VitalBridge.Frontend.Models.EFModels;

public partial class FileStream
{
    public int Id { get; set; }

    public Guid? FileId { get; set; }

    public string FileName { get; set; }

    public virtual ICollection<CareRecipientsImage> CareRecipientsImages { get; set; } = new List<CareRecipientsImage>();

    public virtual ICollection<Category> Categories { get; set; } = new List<Category>();

    public virtual ICollection<EventImage> EventImages { get; set; } = new List<EventImage>();

    public virtual ICollection<FeatureService> FeatureServices { get; set; } = new List<FeatureService>();

    public virtual ICollection<InstitutionAuditImage> InstitutionAuditImages { get; set; } = new List<InstitutionAuditImage>();

    public virtual ICollection<Media> Media { get; set; } = new List<Media>();

    public virtual ICollection<PlateImage> PlateImages { get; set; } = new List<PlateImage>();

    public virtual ICollection<Plate> Plates { get; set; } = new List<Plate>();

    public virtual ICollection<ProductImage> ProductImages { get; set; } = new List<ProductImage>();
}