// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Team1.VitalBridge.Frontend.Models.EFModels;

[Table("FileStream")]
public partial class FileStream
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("fileId")]
    public Guid? FileId { get; set; }

    [Column("fileName")]
    [StringLength(200)]
    public string FileName { get; set; }

    [InverseProperty("File")]
    public virtual ICollection<CareRecipientsImage> CareRecipientsImages { get; set; } = new List<CareRecipientsImage>();

    [InverseProperty("File")]
    public virtual ICollection<Category> Categories { get; set; } = new List<Category>();

    [InverseProperty("File")]
    public virtual ICollection<EventImage> EventImages { get; set; } = new List<EventImage>();

    [InverseProperty("File")]
    public virtual ICollection<FeatureService> FeatureServices { get; set; } = new List<FeatureService>();

    [InverseProperty("File")]
    public virtual ICollection<InstitutionAuditImage> InstitutionAuditImages { get; set; } = new List<InstitutionAuditImage>();

    [InverseProperty("File")]
    public virtual ICollection<Media> Media { get; set; } = new List<Media>();

    [InverseProperty("ImageFile")]
    public virtual ICollection<PlateImage> PlateImages { get; set; } = new List<PlateImage>();

    [InverseProperty("DefaultImageFile")]
    public virtual ICollection<Plate> Plates { get; set; } = new List<Plate>();

    [InverseProperty("File")]
    public virtual ICollection<ProductImage> ProductImages { get; set; } = new List<ProductImage>();
}