// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Team1.VitalBridge.Frontend.Models.EFModels;

public partial class HealthCondition
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Type { get; set; }

    public string Info { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ICollection<CareRecipientHealthCondition> CareRecipientHealthConditions { get; set; } = new List<CareRecipientHealthCondition>();
}