// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Team1.VitalBridge.Frontend.Models.EFModels;

public partial class InstitutionProfile
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public int InstitutionId { get; set; }

    public string Position { get; set; }

    public bool IsResponsible { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual Institution Institution { get; set; }

    public virtual User User { get; set; }
}