// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Team1.VitalBridge.Frontend.Models.EFModels;

public partial class Institution
{
    public int Id { get; set; }

    public string InstitutionCode { get; set; }

    public string Name { get; set; }

    public string Phone { get; set; }

    public string PrincipalName { get; set; }

    public string PrincipalPhone { get; set; }

    public string Email { get; set; }

    public string Status { get; set; }

    public int CityId { get; set; }

    public int TownshipId { get; set; }

    public string Address { get; set; }

    public bool IsPhysicalCheck { get; set; }

    public bool IsBanned { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual City City { get; set; }

    public virtual ICollection<InstitutionAuditImage> InstitutionAuditImages { get; set; } = new List<InstitutionAuditImage>();

    public virtual ICollection<InstitutionProfile> InstitutionProfiles { get; set; } = new List<InstitutionProfile>();

    public virtual ICollection<Organization> Organizations { get; set; } = new List<Organization>();

    public virtual Township Township { get; set; }
}