// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Team1.VitalBridge.Frontend.Models.EFModels;

[Index("UserId", Name = "UQ__Institut__CB9A1CFE0CEBD1A6", IsUnique = true)]
public partial class InstitutionProfile
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("userId")]
    public int UserId { get; set; }

    [Column("institutionId")]
    public int InstitutionId { get; set; }

    [Column("position")]
    [StringLength(20)]
    [Unicode(false)]
    public string Position { get; set; }

    [Column("isResponsible")]
    public bool IsResponsible { get; set; }

    [Column("createdAt", TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [Column("updatedAt", TypeName = "datetime")]
    public DateTime UpdatedAt { get; set; }

    [ForeignKey("InstitutionId")]
    [InverseProperty("InstitutionProfiles")]
    public virtual Institution Institution { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("InstitutionProfile")]
    public virtual User User { get; set; }
}