// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Team1.VitalBridge.Frontend.Models.EFModels;

public partial class Log
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public string Info { get; set; }

    public string Type { get; set; }

    public DateTime CreatedAt { get; set; }

    public string IpAddress { get; set; }

    public virtual User User { get; set; }
}