// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Team1.VitalBridge.Frontend.Models.EFModels;

public partial class Media
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("memberId")]
    public int MemberId { get; set; }

    [Column("contentId")]
    public int? ContentId { get; set; }

    public int FileId { get; set; }

    [Column("mediaTypeId")]
    public int MediaTypeId { get; set; }

    [Required]
    [Column("name")]
    [StringLength(50)]
    public string Name { get; set; }

    [Column("updatedAt", TypeName = "datetime")]
    public DateTime UpdatedAt { get; set; }

    [Column("createdAt", TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [ForeignKey("ContentId")]
    [InverseProperty("Media")]
    public virtual Content Content { get; set; }

    [ForeignKey("FileId")]
    [InverseProperty("Media")]
    public virtual FileStream File { get; set; }

    [ForeignKey("MediaTypeId")]
    [InverseProperty("Media")]
    public virtual MediaType MediaType { get; set; }
}