// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Team1.VitalBridge.Frontend.Models.EFModels;

public partial class Media
{
    public int Id { get; set; }

    public int MemberId { get; set; }

    public int? ContentId { get; set; }

    public int FileId { get; set; }

    public int MediaTypeId { get; set; }

    public string Name { get; set; }

    public DateTime UpdatedAt { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Content Content { get; set; }

    public virtual FileStream File { get; set; }

    public virtual MediaType MediaType { get; set; }
}