// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Team1.VitalBridge.Frontend.Models.EFModels;

public partial class MemberProfile
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public int? CityId { get; set; }

    public int? TownshipId { get; set; }

    public string Address { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual City City { get; set; }

    public virtual Township Township { get; set; }

    public virtual User User { get; set; }
}