// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Team1.VitalBridge.Frontend.Models.EFModels;

public partial class NotifyUser
{
    public int NotifyId { get; set; }

    public int UserId { get; set; }

    public bool IsRead { get; set; }

    public virtual Notify Notify { get; set; }

    public virtual User User { get; set; }
}