// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Team1.VitalBridge.Frontend.Models.EFModels;

public partial class Notify
{
    public int Id { get; set; }

    public string Title { get; set; }

    public string Text { get; set; }

    public string NotifysUrl { get; set; }

    public int CategoriesId { get; set; }

    public DateTime SendDate { get; set; }

    public DateTime? ValidityDate { get; set; }

    public virtual NotifysCategory Categories { get; set; }

    public virtual ICollection<NotifyUser> NotifyUsers { get; set; } = new List<NotifyUser>();
}