// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Team1.VitalBridge.Frontend.Models.EFModels;

[PrimaryKey("NotifyId", "UserId")]
public partial class NotifyUser
{
    [Key]
    [Column("notifyId")]
    public int NotifyId { get; set; }

    [Key]
    [Column("userId")]
    public int UserId { get; set; }

    [Column("isRead")]
    public bool IsRead { get; set; }

    [ForeignKey("NotifyId")]
    [InverseProperty("NotifyUsers")]
    public virtual Notify Notify { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("NotifyUsers")]
    public virtual User User { get; set; }
}