// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Team1.VitalBridge.Frontend.Models.EFModels;

public partial class OrderItem
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("orderId")]
    public int OrderId { get; set; }

    [Column("productId")]
    public int ProductId { get; set; }

    [Required]
    [Column("productName")]
    [StringLength(100)]
    public string ProductName { get; set; }

    [Column("unitPrice", TypeName = "decimal(18, 0)")]
    public decimal UnitPrice { get; set; }

    [Column("quantity")]
    public int Quantity { get; set; }

    [Column("subtotal", TypeName = "decimal(18, 0)")]
    public decimal Subtotal { get; set; }

    [ForeignKey("OrderId")]
    [InverseProperty("OrderItems")]
    public virtual Order Order { get; set; }

    [ForeignKey("ProductId")]
    [InverseProperty("OrderItems")]
    public virtual Product Product { get; set; }
}