// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Team1.VitalBridge.Frontend.Models.EFModels;

public partial class OrderShipMethod
{
    public int Id { get; set; }

    public int OrderId { get; set; }

    public int ShipId { get; set; }

    public int? CityId { get; set; }

    public int? TownshipId { get; set; }

    public string DetailAddress { get; set; }

    public string CarrierCode { get; set; }

    public string HomeTrackingCode { get; set; }

    public string StoreCode { get; set; }

    public string StoreAddress { get; set; }

    public string StoreTrackingCode { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual City City { get; set; }

    public virtual Order Order { get; set; }

    public virtual Ship Ship { get; set; }

    public virtual Township Township { get; set; }
}