// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Team1.VitalBridge.Frontend.Models.EFModels;

public partial class Order
{
    public int Id { get; set; }

    public string OrderNumber { get; set; }

    public int CustomerId { get; set; }

    public decimal ShippingFee { get; set; }

    public int? CouponId { get; set; }

    public decimal? CouponDiscount { get; set; }

    public decimal SubtotalAmount { get; set; }

    public decimal TotalAmount { get; set; }

    public string Note { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual Coupon Coupon { get; set; }

    public virtual CouponRecord CouponRecord { get; set; }

    public virtual User Customer { get; set; }

    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();

    public virtual OrderRecipent OrderRecipent { get; set; }

    public virtual OrderShipMethod OrderShipMethod { get; set; }

    public virtual ICollection<OrderStatus> OrderStatuses { get; set; } = new List<OrderStatus>();

    public virtual Payment Payment { get; set; }
}