// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Team1.VitalBridge.Frontend.Models.EFModels;

public partial class OrderRecipent
{
    public int Id { get; set; }

    public int OrderId { get; set; }

    public string RecipentName { get; set; }

    public string RecipentPhone { get; set; }

    public virtual Order Order { get; set; }
}