// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Team1.VitalBridge.Frontend.Models.EFModels;

[Table("OrderShipMethod")]
[Index("OrderId", Name = "UQ__OrderShi__0809335C00B362C2", IsUnique = true)]
public partial class OrderShipMethod
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("orderId")]
    public int OrderId { get; set; }

    [Column("shipId")]
    public int ShipId { get; set; }

    [Column("cityId")]
    public int? CityId { get; set; }

    [Column("townshipId")]
    public int? TownshipId { get; set; }

    [Column("detailAddress")]
    [StringLength(1000)]
    public string DetailAddress { get; set; }

    [Column("carrierCode")]
    [StringLength(50)]
    public string CarrierCode { get; set; }

    [Column("homeTrackingCode")]
    [StringLength(100)]
    public string HomeTrackingCode { get; set; }

    [Column("storeCode")]
    [StringLength(50)]
    public string StoreCode { get; set; }

    [Column("storeAddress")]
    [StringLength(250)]
    public string StoreAddress { get; set; }

    [Column("storeTrackingCode")]
    [StringLength(100)]
    public string StoreTrackingCode { get; set; }

    [Column("createdAt", TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [Column("updatedAt", TypeName = "datetime")]
    public DateTime UpdatedAt { get; set; }

    [ForeignKey("CityId")]
    [InverseProperty("OrderShipMethods")]
    public virtual City City { get; set; }

    [ForeignKey("OrderId")]
    [InverseProperty("OrderShipMethod")]
    public virtual Order Order { get; set; }

    [ForeignKey("ShipId")]
    [InverseProperty("OrderShipMethods")]
    public virtual Ship Ship { get; set; }

    [ForeignKey("TownshipId")]
    [InverseProperty("OrderShipMethods")]
    public virtual Township Township { get; set; }
}