// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Team1.VitalBridge.Frontend.Models.EFModels;

public partial class OrganizationType
{
    public int Id { get; set; }

    public string Name { get; set; }

    public bool IsActive { get; set; }

    public virtual ICollection<Organization> Organizations { get; set; } = new List<Organization>();
}