// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Team1.VitalBridge.Frontend.Models.EFModels;

public partial class OrganizationRoom
{
    public int Id { get; set; }

    public int? OrganizationId { get; set; }

    public int? RoomTypeId { get; set; }

    public int? MonthlyPrice { get; set; }

    public int? RoomQuantity { get; set; }

    public bool? HasDeposit { get; set; }

    public int? DepositAmount { get; set; }

    public decimal? DepositMonths { get; set; }

    public virtual Organization Organization { get; set; }

    public virtual RoomType RoomType { get; set; }
}