// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Team1.VitalBridge.Frontend.Models.EFModels;

public partial class OrganizationCertificationRequest
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("organizationId")]
    public int OrganizationId { get; set; }

    [Column("submittedAt", TypeName = "datetime")]
    public DateTime? SubmittedAt { get; set; }

    [Column("approvedAt", TypeName = "datetime")]
    public DateTime? ApprovedAt { get; set; }

    [Required]
    [Column("status")]
    [StringLength(50)]
    public string Status { get; set; }

    [Column("reviewerId")]
    public int? ReviewerId { get; set; }

    [Column("rejectionReason")]
    public string RejectionReason { get; set; }

    [ForeignKey("OrganizationId")]
    [InverseProperty("OrganizationCertificationRequests")]
    public virtual Organization Organization { get; set; }
}