// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Team1.VitalBridge.Frontend.Models.EFModels;

public partial class Organization
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("name")]
    [StringLength(100)]
    public string Name { get; set; }

    [Column("bedCount")]
    public int BedCount { get; set; }

    [Column("photoUrl")]
    [StringLength(100)]
    public string PhotoUrl { get; set; }

    [Column("isRecommended")]
    public bool? IsRecommended { get; set; }

    [Column("cityId")]
    public int CityId { get; set; }

    [Column("districtId")]
    public int DistrictId { get; set; }

    [Column("address")]
    [StringLength(100)]
    public string Address { get; set; }

    [Column("typeId")]
    public int TypeId { get; set; }

    [Column("description")]
    [StringLength(100)]
    public string Description { get; set; }

    [Column("isCertified")]
    public bool? IsCertified { get; set; }

    [Column("mapUrl")]
    [StringLength(100)]
    public string MapUrl { get; set; }

    [Column("ageLimits")]
    [StringLength(100)]
    public string AgeLimits { get; set; }

    [Column("isDeleted")]
    public bool IsDeleted { get; set; }

    [Column("isActive")]
    public bool IsActive { get; set; }

    [Column("institutionId")]
    public int? InstitutionId { get; set; }

    [ForeignKey("CityId")]
    [InverseProperty("Organizations")]
    public virtual City City { get; set; }

    [ForeignKey("DistrictId")]
    [InverseProperty("Organizations")]
    public virtual Township District { get; set; }

    [ForeignKey("InstitutionId")]
    [InverseProperty("Organizations")]
    public virtual Institution Institution { get; set; }

    [InverseProperty("Organization")]
    public virtual ICollection<OrganizationCertificationRequest> OrganizationCertificationRequests { get; set; } = new List<OrganizationCertificationRequest>();

    [InverseProperty("Organization")]
    public virtual ICollection<OrganizationFeatureService> OrganizationFeatureServices { get; set; } = new List<OrganizationFeatureService>();

    [InverseProperty("Organization")]
    public virtual ICollection<OrganizationRoom> OrganizationRooms { get; set; } = new List<OrganizationRoom>();

    [InverseProperty("Organization")]
    public virtual ICollection<OrganizationServiceTarget> OrganizationServiceTargets { get; set; } = new List<OrganizationServiceTarget>();

    [InverseProperty("Organization")]
    public virtual ICollection<OrganizationSubsidyInfo> OrganizationSubsidyInfos { get; set; } = new List<OrganizationSubsidyInfo>();

    [ForeignKey("TypeId")]
    [InverseProperty("Organizations")]
    public virtual OrganizationType Type { get; set; }
}