// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Team1.VitalBridge.Frontend.Models.EFModels;

public partial class OrganizationServiceTarget
{
    public int Id { get; set; }

    public int OrganizationId { get; set; }

    public int ServiceTargetId { get; set; }

    public virtual Organization Organization { get; set; }

    public virtual ServiceTarget ServiceTarget { get; set; }
}