// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Team1.VitalBridge.Frontend.Models.EFModels;

public partial class Organization
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int BedCount { get; set; }

    public string PhotoUrl { get; set; }

    public bool? IsRecommended { get; set; }

    public int CityId { get; set; }

    public int DistrictId { get; set; }

    public string Address { get; set; }

    public int TypeId { get; set; }

    public string Description { get; set; }

    public bool? IsCertified { get; set; }

    public string MapUrl { get; set; }

    public string AgeLimits { get; set; }

    public bool IsDeleted { get; set; }

    public bool IsActive { get; set; }

    public int? InstitutionId { get; set; }

    public virtual City City { get; set; }

    public virtual Township District { get; set; }

    public virtual Institution Institution { get; set; }

    public virtual ICollection<OrganizationCertificationRequest> OrganizationCertificationRequests { get; set; } = new List<OrganizationCertificationRequest>();

    public virtual ICollection<OrganizationFeatureService> OrganizationFeatureServices { get; set; } = new List<OrganizationFeatureService>();

    public virtual ICollection<OrganizationRoom> OrganizationRooms { get; set; } = new List<OrganizationRoom>();

    public virtual ICollection<OrganizationServiceTarget> OrganizationServiceTargets { get; set; } = new List<OrganizationServiceTarget>();

    public virtual ICollection<OrganizationSubsidyInfo> OrganizationSubsidyInfos { get; set; } = new List<OrganizationSubsidyInfo>();

    public virtual OrganizationType Type { get; set; }
}