// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Team1.VitalBridge.Frontend.Models.EFModels;

public partial class OrganizationCertificationRequest
{
    public int Id { get; set; }

    public int OrganizationId { get; set; }

    public DateTime? SubmittedAt { get; set; }

    public DateTime? ApprovedAt { get; set; }

    public string Status { get; set; }

    public int? ReviewerId { get; set; }

    public string RejectionReason { get; set; }

    public virtual Organization Organization { get; set; }
}