// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Team1.VitalBridge.Frontend.Models.EFModels;

public partial class OrganizationFeatureService
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("organizationId")]
    public int OrganizationId { get; set; }

    [Column("featureServiceId")]
    public int FeatureServiceId { get; set; }

    [ForeignKey("FeatureServiceId")]
    [InverseProperty("OrganizationFeatureServices")]
    public virtual FeatureService FeatureService { get; set; }

    [ForeignKey("OrganizationId")]
    [InverseProperty("OrganizationFeatureServices")]
    public virtual Organization Organization { get; set; }
}