// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Team1.VitalBridge.Frontend.Models.EFModels;

public partial class Payment
{
    public int Id { get; set; }

    public int OrderId { get; set; }

    public int PayMethodId { get; set; }

    public int Status { get; set; }

    public DateTime? PaidAt { get; set; }

    public decimal Amount { get; set; }

    public string TransactionId { get; set; }

    public DateTime CreatAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual Order Order { get; set; }

    public virtual PaymentMethod PayMethod { get; set; }

    public virtual PaymentStatus StatusNavigation { get; set; }
}