// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Team1.VitalBridge.Frontend.Models.EFModels;

public partial class Permission
{
    public int Id { get; set; }

    public string PermissionCode { get; set; }

    public string Name { get; set; }

    public string Info { get; set; }

    public bool IsActive { get; set; }

    public string PermissionType { get; set; }

    public bool IsSystemDefault { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public DateTime? DeprecatedAt { get; set; }

    public virtual ICollection<RolePermission> RolePermissions { get; set; } = new List<RolePermission>();
}