// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Team1.VitalBridge.Frontend.Models.EFModels;

[Table("PlateImage")]
public partial class PlateImage
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("plateId")]
    public int PlateId { get; set; }

    [Column("introduct")]
    [StringLength(50)]
    public string Introduct { get; set; }

    [Column("imageFileId")]
    public int ImageFileId { get; set; }

    [Column("startDate")]
    public DateOnly StartDate { get; set; }

    [Column("endDate")]
    public DateOnly EndDate { get; set; }

    [Column("displayOrder")]
    public int? DisplayOrder { get; set; }

    [Column("clickUrl")]
    [StringLength(500)]
    public string ClickUrl { get; set; }

    [Column("clickNumber")]
    public int? ClickNumber { get; set; }

    [ForeignKey("ImageFileId")]
    [InverseProperty("PlateImages")]
    public virtual FileStream ImageFile { get; set; }

    [ForeignKey("PlateId")]
    [InverseProperty("PlateImages")]
    public virtual Plate Plate { get; set; }
}