// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Team1.VitalBridge.Frontend.Models.EFModels;

public partial class Plate
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Route { get; set; }

    public string Location { get; set; }

    public bool Enable { get; set; }

    public string DefaultImageIntroduct { get; set; }

    public int DefaultImageFileId { get; set; }

    public string DefaultImageClickUrl { get; set; }

    public virtual FileStream DefaultImageFile { get; set; }

    public virtual ICollection<PlateImage> PlateImages { get; set; } = new List<PlateImage>();
}