// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Team1.VitalBridge.Frontend.Models.EFModels;

[Table("Plate")]
public partial class Plate
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [StringLength(50)]
    public string Name { get; set; }

    [Required]
    [StringLength(50)]
    public string Route { get; set; }

    [Required]
    [StringLength(200)]
    public string Location { get; set; }

    public bool Enable { get; set; }

    [Column("defaultImageIntroduct")]
    [StringLength(50)]
    public string DefaultImageIntroduct { get; set; }

    [Column("defaultImageFileId")]
    public int DefaultImageFileId { get; set; }

    [Column("defaultImageClickUrl")]
    [StringLength(500)]
    public string DefaultImageClickUrl { get; set; }

    [ForeignKey("DefaultImageFileId")]
    [InverseProperty("Plates")]
    public virtual FileStream DefaultImageFile { get; set; }

    [InverseProperty("Plate")]
    public virtual ICollection<PlateImage> PlateImages { get; set; } = new List<PlateImage>();
}