// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Team1.VitalBridge.Frontend.Models.EFModels;

public partial class PlateImage
{
    public int Id { get; set; }

    public int PlateId { get; set; }

    public string Introduct { get; set; }

    public int ImageFileId { get; set; }

    public DateOnly StartDate { get; set; }

    public DateOnly EndDate { get; set; }

    public int? DisplayOrder { get; set; }

    public string ClickUrl { get; set; }

    public int? ClickNumber { get; set; }

    public virtual FileStream ImageFile { get; set; }

    public virtual Plate Plate { get; set; }
}