// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Team1.VitalBridge.Frontend.Models.EFModels;

public partial class ProductNote
{
    public int Id { get; set; }

    public string ShoppNote { get; set; }

    public string DeliveryAndPayMethod { get; set; }

    public DateTime CreatedAt { get; set; }
}