// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Team1.VitalBridge.Frontend.Models.EFModels;

public partial class ProductShip
{
    public int Id { get; set; }

    public int ProductId { get; set; }

    public int ShipId { get; set; }

    public bool IsActive { get; set; }

    public virtual Product Product { get; set; }

    public virtual Ship Ship { get; set; }
}