// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Team1.VitalBridge.Frontend.Models.EFModels;

public partial class RoomType
{
    public int Id { get; set; }

    public string Name { get; set; }

    public virtual ICollection<OrganizationRoom> OrganizationRooms { get; set; } = new List<OrganizationRoom>();
}