// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Team1.VitalBridge.Frontend.Models.EFModels;

public partial class ShippingRule
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("name")]
    [StringLength(100)]
    public string Name { get; set; }

    [Column("miniOrderAmout")]
    public int MiniOrderAmout { get; set; }

    [Column("startAt", TypeName = "datetime")]
    public DateTime StartAt { get; set; }

    [Column("endAt", TypeName = "datetime")]
    public DateTime EndAt { get; set; }

    [Column("isActive")]
    public bool IsActive { get; set; }

    [Column("createAt", TypeName = "datetime")]
    public DateTime CreateAt { get; set; }

    [Column("updatedAt", TypeName = "datetime")]
    public DateTime UpdatedAt { get; set; }
}