// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Team1.VitalBridge.Frontend.Models.EFModels;

public partial class Ship
{
    public int Id { get; set; }

    public string ShipMethodName { get; set; }

    public decimal ShipCost { get; set; }

    public bool? IsActive { get; set; }

    public virtual ICollection<OrderShipMethod> OrderShipMethods { get; set; } = new List<OrderShipMethod>();

    public virtual ICollection<ProductShip> ProductShips { get; set; } = new List<ProductShip>();
}