// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Team1.VitalBridge.Frontend.Models.EFModels;

public partial class ShopHomePageBanner
{
    public int Id { get; set; }

    public int Position { get; set; }

    public string ShopBannerUrl { get; set; }

    public string LandingPageUrl { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreateAt { get; set; }

    public DateTime Updated { get; set; }
}