// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Team1.VitalBridge.Frontend.Models.EFModels;

public partial class SubsidyInfo
{
    public int Id { get; set; }

    public string Description { get; set; }

    public virtual ICollection<OrganizationSubsidyInfo> OrganizationSubsidyInfos { get; set; } = new List<OrganizationSubsidyInfo>();
}