// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Team1.VitalBridge.Frontend.Models.EFModels;

public partial class Township
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("cityId")]
    public int CityId { get; set; }

    [Required]
    [Column("name")]
    [StringLength(10)]
    [Unicode(false)]
    public string Name { get; set; }

    [Required]
    [Column("postalCode")]
    [StringLength(6)]
    [Unicode(false)]
    public string PostalCode { get; set; }

    [InverseProperty("Township")]
    public virtual ICollection<CareRecipient> CareRecipients { get; set; } = new List<CareRecipient>();

    [ForeignKey("CityId")]
    [InverseProperty("Townships")]
    public virtual City City { get; set; }

    [InverseProperty("Township")]
    public virtual ICollection<EmergencyContact> EmergencyContacts { get; set; } = new List<EmergencyContact>();

    [InverseProperty("Township")]
    public virtual ICollection<Event> Events { get; set; } = new List<Event>();

    [InverseProperty("Township")]
    public virtual ICollection<Institution> Institutions { get; set; } = new List<Institution>();

    [InverseProperty("Township")]
    public virtual ICollection<MemberProfile> MemberProfiles { get; set; } = new List<MemberProfile>();

    [InverseProperty("Township")]
    public virtual ICollection<OrderShipMethod> OrderShipMethods { get; set; } = new List<OrderShipMethod>();

    [InverseProperty("District")]
    public virtual ICollection<Organization> Organizations { get; set; } = new List<Organization>();
}