// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Team1.VitalBridge.Frontend.Models.EFModels;

public partial class Township
{
    public int Id { get; set; }

    public int CityId { get; set; }

    public string Name { get; set; }

    public string PostalCode { get; set; }

    public virtual ICollection<CareRecipient> CareRecipients { get; set; } = new List<CareRecipient>();

    public virtual City City { get; set; }

    public virtual ICollection<EmergencyContact> EmergencyContacts { get; set; } = new List<EmergencyContact>();

    public virtual ICollection<Event> Events { get; set; } = new List<Event>();

    public virtual ICollection<Institution> Institutions { get; set; } = new List<Institution>();

    public virtual ICollection<MemberProfile> MemberProfiles { get; set; } = new List<MemberProfile>();

    public virtual ICollection<OrderShipMethod> OrderShipMethods { get; set; } = new List<OrderShipMethod>();

    public virtual ICollection<Organization> Organizations { get; set; } = new List<Organization>();
}