// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Team1.VitalBridge.Frontend.Models.EFModels;

[Index("Email", "AccountType", Name = "UQ__Users__C98484590D2FCEF6", IsUnique = true)]
[Index("UserId", Name = "UQ__Users__CB9A1CFED99D2BE0", IsUnique = true)]
public partial class User
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("userId")]
    [StringLength(50)]
    [Unicode(false)]
    public string UserId { get; set; }

    [Required]
    [Column("name")]
    [StringLength(20)]
    [Unicode(false)]
    public string Name { get; set; }

    [Required]
    [Column("email")]
    [StringLength(256)]
    [Unicode(false)]
    public string Email { get; set; }

    [Column("password")]
    [StringLength(100)]
    [Unicode(false)]
    public string Password { get; set; }

    [Column("phone")]
    [StringLength(10)]
    [Unicode(false)]
    public string Phone { get; set; }

    [Required]
    [Column("status")]
    [StringLength(20)]
    [Unicode(false)]
    public string Status { get; set; }

    [Column("confirmCode")]
    [StringLength(50)]
    [Unicode(false)]
    public string ConfirmCode { get; set; }

    [Column("confirmCodeExpiresAt", TypeName = "datetime")]
    public DateTime? ConfirmCodeExpiresAt { get; set; }

    [Column("resetPasswordConfirmCode")]
    [StringLength(50)]
    [Unicode(false)]
    public string ResetPasswordConfirmCode { get; set; }

    [Column("resetPasswordConfirmCodeExpiresAt", TypeName = "datetime")]
    public DateTime? ResetPasswordConfirmCodeExpiresAt { get; set; }

    [Column("createdAt", TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [Column("updatedAt", TypeName = "datetime")]
    public DateTime UpdatedAt { get; set; }

    [Column("lastLoginAt", TypeName = "datetime")]
    public DateTime? LastLoginAt { get; set; }

    [Required]
    [Column("accountType")]
    [StringLength(30)]
    [Unicode(false)]
    public string AccountType { get; set; }

    [Column("failedLoginCount")]
    public int? FailedLoginCount { get; set; }

    [Column("lockedUntil", TypeName = "datetime")]
    public DateTime? LockedUntil { get; set; }

    [Column("lastPasswordResetEmailAt", TypeName = "datetime")]
    public DateTime? LastPasswordResetEmailAt { get; set; }

    [InverseProperty("User")]
    public virtual AdminProfile AdminProfile { get; set; }

    [InverseProperty("InviterUser")]
    public virtual ICollection<CareRecipientInvitation> CareRecipientInvitations { get; set; } = new List<CareRecipientInvitation>();

    [InverseProperty("Customer")]
    public virtual Cart Cart { get; set; }

    [InverseProperty("Member")]
    public virtual ICollection<Comment> Comments { get; set; } = new List<Comment>();

    [InverseProperty("Member")]
    public virtual ICollection<Content> Contents { get; set; } = new List<Content>();

    [InverseProperty("Customer")]
    public virtual ICollection<CouponRecord> CouponRecords { get; set; } = new List<CouponRecord>();

    [InverseProperty("User")]
    public virtual ICollection<EmergencyContact> EmergencyContacts { get; set; } = new List<EmergencyContact>();

    [InverseProperty("User")]
    public virtual ICollection<EventParticipant> EventParticipants { get; set; } = new List<EventParticipant>();

    [InverseProperty("User")]
    public virtual ICollection<ExternalLogin> ExternalLogins { get; set; } = new List<ExternalLogin>();

    [InverseProperty("Customer")]
    public virtual ICollection<Favorite> Favorites { get; set; } = new List<Favorite>();

    [InverseProperty("User")]
    public virtual InstitutionProfile InstitutionProfile { get; set; }

    [InverseProperty("User")]
    public virtual ICollection<Log> Logs { get; set; } = new List<Log>();

    [InverseProperty("User")]
    public virtual MemberProfile MemberProfile { get; set; }

    [InverseProperty("User")]
    public virtual ICollection<NotifyUser> NotifyUsers { get; set; } = new List<NotifyUser>();

    [InverseProperty("Customer")]
    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    [InverseProperty("User")]
    public virtual ICollection<UserCareRecipient> UserCareRecipients { get; set; } = new List<UserCareRecipient>();

    [InverseProperty("User")]
    public virtual ICollection<UserRole> UserRoles { get; set; } = new List<UserRole>();
}