// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Team1.VitalBridge.Frontend.Models.EFModels;

public partial class UserCareRecipient
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("userId")]
    public int UserId { get; set; }

    [Column("careRecipientId")]
    public int CareRecipientId { get; set; }

    [Required]
    [Column("relationship")]
    [StringLength(20)]
    [Unicode(false)]
    public string Relationship { get; set; }

    [Column("createdAt", TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [Required]
    [Column("permissionLevel")]
    [StringLength(30)]
    [Unicode(false)]
    public string PermissionLevel { get; set; }

    [ForeignKey("CareRecipientId")]
    [InverseProperty("UserCareRecipients")]
    public virtual CareRecipient CareRecipient { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("UserCareRecipients")]
    public virtual User User { get; set; }
}