// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Team1.VitalBridge.Frontend.Models.EFModels;

public partial class UserCareRecipient
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public int CareRecipientId { get; set; }

    public string Relationship { get; set; }

    public DateTime CreatedAt { get; set; }

    public string PermissionLevel { get; set; }

    public virtual CareRecipient CareRecipient { get; set; }

    public virtual User User { get; set; }
}