// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Team1.VitalBridge.Frontend.Models.EFModels;

public partial class User
{
    public int Id { get; set; }

    public string UserId { get; set; }

    public string Name { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public string Phone { get; set; }

    public string Status { get; set; }

    public string ConfirmCode { get; set; }

    public DateTime? ConfirmCodeExpiresAt { get; set; }

    public string ResetPasswordConfirmCode { get; set; }

    public DateTime? ResetPasswordConfirmCodeExpiresAt { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public DateTime? LastLoginAt { get; set; }

    public string AccountType { get; set; }

    public int? FailedLoginCount { get; set; }

    public DateTime? LockedUntil { get; set; }

    public virtual AdminProfile AdminProfile { get; set; }

    public virtual ICollection<CareRecipientInvitation> CareRecipientInvitations { get; set; } = new List<CareRecipientInvitation>();

    public virtual Cart Cart { get; set; }

    public virtual ICollection<CouponRecord> CouponRecords { get; set; } = new List<CouponRecord>();

    public virtual ICollection<EmergencyContact> EmergencyContacts { get; set; } = new List<EmergencyContact>();

    public virtual ICollection<EventParticipant> EventParticipants { get; set; } = new List<EventParticipant>();

    public virtual ICollection<ExternalLogin> ExternalLogins { get; set; } = new List<ExternalLogin>();

    public virtual ICollection<Favorite> Favorites { get; set; } = new List<Favorite>();

    public virtual InstitutionProfile InstitutionProfile { get; set; }

    public virtual ICollection<Log> Logs { get; set; } = new List<Log>();

    public virtual MemberProfile MemberProfile { get; set; }

    public virtual ICollection<NotifyUser> NotifyUsers { get; set; } = new List<NotifyUser>();

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual ICollection<UserCareRecipient> UserCareRecipients { get; set; } = new List<UserCareRecipient>();

    public virtual ICollection<UserRole> UserRoles { get; set; } = new List<UserRole>();
}